version: "2"
sql:
  - schema: "./schema.sql"
    queries: "./queries/"
    engine: "postgresql"
    gen:
      go:
        package: "repository"
        sql_package: "pgx/v5"
        out: "./repository"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
          - db_type: "ulid"
            go_type:
              import: "github.com/oklog/ulid/v2"
              type: "ULID"
