// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: rpc_wallet_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_DepositAsset_FullMethodName                  = "/proto.WalletService/DepositAsset"
	WalletService_WithdrawAsset_FullMethodName                 = "/proto.WalletService/WithdrawAsset"
	WalletService_TransferAsset_FullMethodName                 = "/proto.WalletService/TransferAsset"
	WalletService_ExchangeAsset_FullMethodName                 = "/proto.WalletService/ExchangeAsset"
	WalletService_ContextUserAccounts_FullMethodName           = "/proto.WalletService/ContextUserAccounts"
	WalletService_ContextUserWalletTransactions_FullMethodName = "/proto.WalletService/ContextUserWalletTransactions"
	WalletService_GetAccountTransfers_FullMethodName           = "/proto.WalletService/GetAccountTransfers"
	WalletService_QueryTransfers_FullMethodName                = "/proto.WalletService/QueryTransfers"
	WalletService_LookupTransfers_FullMethodName               = "/proto.WalletService/LookupTransfers"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletService provides comprehensive wallet management endpoints for asset operations.
// All endpoints require Bearer token authentication and support both gRPC and HTTP/JSON.
type WalletServiceClient interface {
	// DepositAsset adds funds to the authenticated user's wallet account for a specific asset.
	// This operation creates a credit transfer in TigerBeetle from a system account to the user's account.
	DepositAsset(ctx context.Context, in *DepositAssetRequest, opts ...grpc.CallOption) (*DepositAssetResponse, error)
	// WithdrawAsset removes funds from the authenticated user's wallet account for a specific asset.
	// This operation creates a debit transfer in TigerBeetle from the user's account to a system account.
	WithdrawAsset(ctx context.Context, in *WithdrawAssetRequest, opts ...grpc.CallOption) (*WithdrawAssetResponse, error)
	// TransferAsset moves funds from the authenticated user's wallet to another user's wallet.
	// This operation creates a transfer in TigerBeetle between two user accounts.
	TransferAsset(ctx context.Context, in *TransferAssetRequest, opts ...grpc.CallOption) (*TransferAssetResponse, error)
	// ExchangeAsset converts one asset to another within the authenticated user's wallet.
	// This operation creates two linked transfers in TigerBeetle for atomic exchange.
	ExchangeAsset(ctx context.Context, in *ExchangeAssetRequest, opts ...grpc.CallOption) (*ExchangeAssetResponse, error)
	// ContextUserAccounts retrieves the authenticated user's account information include asset wallets.
	// This endpoint is cached for 120 seconds to reduce database load.
	ContextUserAccounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletResponse, error)
	// ContextUserWalletTransactions retrieves the authenticated user's transaction history.
	// This endpoint is cached for 120 seconds to reduce database load.
	ContextUserWalletTransactions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletTransactionsResponse, error)
	// GetAccountTransfers queries TigerBeetle transfers for a specific account.
	// This is a low-level endpoint for direct TigerBeetle transfer queries.
	GetAccountTransfers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAccountTransfersResponse, error)
	// QueryTransfers queries TigerBeetle transfers by metadata and filter criteria.
	// This is a low-level endpoint for advanced transfer queries.
	QueryTransfers(ctx context.Context, in *QueryTransfersRequest, opts ...grpc.CallOption) (*QueryTransfersResponse, error)
	// LookupTransfers fetches specific TigerBeetle transfers by their IDs.
	// This is the most efficient way to retrieve known transfers.
	LookupTransfers(ctx context.Context, in *LookupTransfersRequest, opts ...grpc.CallOption) (*LookupTransfersResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) DepositAsset(ctx context.Context, in *DepositAssetRequest, opts ...grpc.CallOption) (*DepositAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_DepositAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) WithdrawAsset(ctx context.Context, in *WithdrawAssetRequest, opts ...grpc.CallOption) (*WithdrawAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_WithdrawAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) TransferAsset(ctx context.Context, in *TransferAssetRequest, opts ...grpc.CallOption) (*TransferAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_TransferAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ExchangeAsset(ctx context.Context, in *ExchangeAssetRequest, opts ...grpc.CallOption) (*ExchangeAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_ExchangeAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ContextUserAccounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextUserWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_ContextUserAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ContextUserWalletTransactions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextUserWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, WalletService_ContextUserWalletTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetAccountTransfers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAccountTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountTransfersResponse)
	err := c.cc.Invoke(ctx, WalletService_GetAccountTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) QueryTransfers(ctx context.Context, in *QueryTransfersRequest, opts ...grpc.CallOption) (*QueryTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTransfersResponse)
	err := c.cc.Invoke(ctx, WalletService_QueryTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) LookupTransfers(ctx context.Context, in *LookupTransfersRequest, opts ...grpc.CallOption) (*LookupTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupTransfersResponse)
	err := c.cc.Invoke(ctx, WalletService_LookupTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// WalletService provides comprehensive wallet management endpoints for asset operations.
// All endpoints require Bearer token authentication and support both gRPC and HTTP/JSON.
type WalletServiceServer interface {
	// DepositAsset adds funds to the authenticated user's wallet account for a specific asset.
	// This operation creates a credit transfer in TigerBeetle from a system account to the user's account.
	DepositAsset(context.Context, *DepositAssetRequest) (*DepositAssetResponse, error)
	// WithdrawAsset removes funds from the authenticated user's wallet account for a specific asset.
	// This operation creates a debit transfer in TigerBeetle from the user's account to a system account.
	WithdrawAsset(context.Context, *WithdrawAssetRequest) (*WithdrawAssetResponse, error)
	// TransferAsset moves funds from the authenticated user's wallet to another user's wallet.
	// This operation creates a transfer in TigerBeetle between two user accounts.
	TransferAsset(context.Context, *TransferAssetRequest) (*TransferAssetResponse, error)
	// ExchangeAsset converts one asset to another within the authenticated user's wallet.
	// This operation creates two linked transfers in TigerBeetle for atomic exchange.
	ExchangeAsset(context.Context, *ExchangeAssetRequest) (*ExchangeAssetResponse, error)
	// ContextUserAccounts retrieves the authenticated user's account information include asset wallets.
	// This endpoint is cached for 120 seconds to reduce database load.
	ContextUserAccounts(context.Context, *emptypb.Empty) (*ContextUserWalletResponse, error)
	// ContextUserWalletTransactions retrieves the authenticated user's transaction history.
	// This endpoint is cached for 120 seconds to reduce database load.
	ContextUserWalletTransactions(context.Context, *emptypb.Empty) (*ContextUserWalletTransactionsResponse, error)
	// GetAccountTransfers queries TigerBeetle transfers for a specific account.
	// This is a low-level endpoint for direct TigerBeetle transfer queries.
	GetAccountTransfers(context.Context, *emptypb.Empty) (*GetAccountTransfersResponse, error)
	// QueryTransfers queries TigerBeetle transfers by metadata and filter criteria.
	// This is a low-level endpoint for advanced transfer queries.
	QueryTransfers(context.Context, *QueryTransfersRequest) (*QueryTransfersResponse, error)
	// LookupTransfers fetches specific TigerBeetle transfers by their IDs.
	// This is the most efficient way to retrieve known transfers.
	LookupTransfers(context.Context, *LookupTransfersRequest) (*LookupTransfersResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) DepositAsset(context.Context, *DepositAssetRequest) (*DepositAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DepositAsset not implemented")
}
func (UnimplementedWalletServiceServer) WithdrawAsset(context.Context, *WithdrawAssetRequest) (*WithdrawAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawAsset not implemented")
}
func (UnimplementedWalletServiceServer) TransferAsset(context.Context, *TransferAssetRequest) (*TransferAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferAsset not implemented")
}
func (UnimplementedWalletServiceServer) ExchangeAsset(context.Context, *ExchangeAssetRequest) (*ExchangeAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeAsset not implemented")
}
func (UnimplementedWalletServiceServer) ContextUserAccounts(context.Context, *emptypb.Empty) (*ContextUserWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContextUserAccounts not implemented")
}
func (UnimplementedWalletServiceServer) ContextUserWalletTransactions(context.Context, *emptypb.Empty) (*ContextUserWalletTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContextUserWalletTransactions not implemented")
}
func (UnimplementedWalletServiceServer) GetAccountTransfers(context.Context, *emptypb.Empty) (*GetAccountTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountTransfers not implemented")
}
func (UnimplementedWalletServiceServer) QueryTransfers(context.Context, *QueryTransfersRequest) (*QueryTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTransfers not implemented")
}
func (UnimplementedWalletServiceServer) LookupTransfers(context.Context, *LookupTransfersRequest) (*LookupTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupTransfers not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_DepositAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DepositAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_DepositAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DepositAsset(ctx, req.(*DepositAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_WithdrawAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).WithdrawAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_WithdrawAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).WithdrawAsset(ctx, req.(*WithdrawAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_TransferAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).TransferAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_TransferAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).TransferAsset(ctx, req.(*TransferAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ExchangeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ExchangeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ExchangeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ExchangeAsset(ctx, req.(*ExchangeAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ContextUserAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ContextUserAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ContextUserAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ContextUserAccounts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ContextUserWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ContextUserWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ContextUserWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ContextUserWalletTransactions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetAccountTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAccountTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetAccountTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAccountTransfers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_QueryTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).QueryTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_QueryTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).QueryTransfers(ctx, req.(*QueryTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_LookupTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).LookupTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_LookupTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).LookupTransfers(ctx, req.(*LookupTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositAsset",
			Handler:    _WalletService_DepositAsset_Handler,
		},
		{
			MethodName: "WithdrawAsset",
			Handler:    _WalletService_WithdrawAsset_Handler,
		},
		{
			MethodName: "TransferAsset",
			Handler:    _WalletService_TransferAsset_Handler,
		},
		{
			MethodName: "ExchangeAsset",
			Handler:    _WalletService_ExchangeAsset_Handler,
		},
		{
			MethodName: "ContextUserAccounts",
			Handler:    _WalletService_ContextUserAccounts_Handler,
		},
		{
			MethodName: "ContextUserWalletTransactions",
			Handler:    _WalletService_ContextUserWalletTransactions_Handler,
		},
		{
			MethodName: "GetAccountTransfers",
			Handler:    _WalletService_GetAccountTransfers_Handler,
		},
		{
			MethodName: "QueryTransfers",
			Handler:    _WalletService_QueryTransfers_Handler,
		},
		{
			MethodName: "LookupTransfers",
			Handler:    _WalletService_LookupTransfers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_wallet_service.proto",
}
