// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_wallet.model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wallet message containing all wallet data and nested entities
type Wallet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wallet public identifier to hide real database id of wallet
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// wallet ban status
	Banned bool `protobuf:"varint,2,opt,name=banned,proto3" json:"banned,omitempty"`
	// metadata contains wallet meta data
	MetaData map[string]string `protobuf:"bytes,3,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// wallet expiration time
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// wallet creation time
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// wallet update time
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// wallet deletion time
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_rpc_wallet_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_model_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Wallet) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *Wallet) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Wallet) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Wallet) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_rpc_wallet_model_proto protoreflect.FileDescriptor

const file_rpc_wallet_model_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_wallet.model.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x03\n" +
	"\x06Wallet\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x16\n" +
	"\x06banned\x18\x02 \x01(\bR\x06banned\x128\n" +
	"\tmeta_data\x18\x03 \x03(\v2\x1b.proto.Wallet.MetaDataEntryR\bmetaData\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_wallet_model_proto_rawDescOnce sync.Once
	file_rpc_wallet_model_proto_rawDescData []byte
)

func file_rpc_wallet_model_proto_rawDescGZIP() []byte {
	file_rpc_wallet_model_proto_rawDescOnce.Do(func() {
		file_rpc_wallet_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_wallet_model_proto_rawDesc), len(file_rpc_wallet_model_proto_rawDesc)))
	})
	return file_rpc_wallet_model_proto_rawDescData
}

var file_rpc_wallet_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_wallet_model_proto_goTypes = []any{
	(*Wallet)(nil),                // 0: proto.Wallet
	nil,                           // 1: proto.Wallet.MetaDataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_rpc_wallet_model_proto_depIdxs = []int32{
	1, // 0: proto.Wallet.meta_data:type_name -> proto.Wallet.MetaDataEntry
	2, // 1: proto.Wallet.expires_at:type_name -> google.protobuf.Timestamp
	2, // 2: proto.Wallet.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: proto.Wallet.updated_at:type_name -> google.protobuf.Timestamp
	2, // 4: proto.Wallet.deleted_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_wallet_model_proto_init() }
func file_rpc_wallet_model_proto_init() {
	if File_rpc_wallet_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_wallet_model_proto_rawDesc), len(file_rpc_wallet_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_wallet_model_proto_goTypes,
		DependencyIndexes: file_rpc_wallet_model_proto_depIdxs,
		MessageInfos:      file_rpc_wallet_model_proto_msgTypes,
	}.Build()
	File_rpc_wallet_model_proto = out.File
	file_rpc_wallet_model_proto_goTypes = nil
	file_rpc_wallet_model_proto_depIdxs = nil
}
