// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: rpc_wallet_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_DepositeAsset_FullMethodName                 = "/proto.WalletService/DepositeAsset"
	WalletService_WithdrawAsset_FullMethodName                 = "/proto.WalletService/WithdrawAsset"
	WalletService_TransferAsset_FullMethodName                 = "/proto.WalletService/TransferAsset"
	WalletService_ExcahngeAsset_FullMethodName                 = "/proto.WalletService/ExcahngeAsset"
	WalletService_ContextUserWallet_FullMethodName             = "/proto.WalletService/ContextUserWallet"
	WalletService_ContextUserWalletTransactions_FullMethodName = "/proto.WalletService/ContextUserWalletTransactions"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletService service provides user wallet management endpoints
type WalletServiceClient interface {
	// Deposite asset to user wallet.
	DepositeAsset(ctx context.Context, in *DepositeAssetRequest, opts ...grpc.CallOption) (*DepositeAssetResponse, error)
	// Withdraw asset from user wallet.
	WithdrawAsset(ctx context.Context, in *WithdrawAssetRequest, opts ...grpc.CallOption) (*WithdrawAssetResponse, error)
	// Transfer asset from user wallet to another user wallet.
	TransferAsset(ctx context.Context, in *TransferAssetRequest, opts ...grpc.CallOption) (*TransferAssetResponse, error)
	// Exchange asset from user wallet to another asset.
	ExcahngeAsset(ctx context.Context, in *ExchangeAssetRequest, opts ...grpc.CallOption) (*ExchangeAssetResponse, error)
	// Get context user wallet data.
	ContextUserWallet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletResponse, error)
	// Get context user wallet transaction list.
	ContextUserWalletTransactions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletTransactionsResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) DepositeAsset(ctx context.Context, in *DepositeAssetRequest, opts ...grpc.CallOption) (*DepositeAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositeAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_DepositeAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) WithdrawAsset(ctx context.Context, in *WithdrawAssetRequest, opts ...grpc.CallOption) (*WithdrawAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_WithdrawAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) TransferAsset(ctx context.Context, in *TransferAssetRequest, opts ...grpc.CallOption) (*TransferAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_TransferAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ExcahngeAsset(ctx context.Context, in *ExchangeAssetRequest, opts ...grpc.CallOption) (*ExchangeAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeAssetResponse)
	err := c.cc.Invoke(ctx, WalletService_ExcahngeAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ContextUserWallet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextUserWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_ContextUserWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ContextUserWalletTransactions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextUserWalletTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextUserWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, WalletService_ContextUserWalletTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// WalletService service provides user wallet management endpoints
type WalletServiceServer interface {
	// Deposite asset to user wallet.
	DepositeAsset(context.Context, *DepositeAssetRequest) (*DepositeAssetResponse, error)
	// Withdraw asset from user wallet.
	WithdrawAsset(context.Context, *WithdrawAssetRequest) (*WithdrawAssetResponse, error)
	// Transfer asset from user wallet to another user wallet.
	TransferAsset(context.Context, *TransferAssetRequest) (*TransferAssetResponse, error)
	// Exchange asset from user wallet to another asset.
	ExcahngeAsset(context.Context, *ExchangeAssetRequest) (*ExchangeAssetResponse, error)
	// Get context user wallet data.
	ContextUserWallet(context.Context, *emptypb.Empty) (*ContextUserWalletResponse, error)
	// Get context user wallet transaction list.
	ContextUserWalletTransactions(context.Context, *emptypb.Empty) (*ContextUserWalletTransactionsResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) DepositeAsset(context.Context, *DepositeAssetRequest) (*DepositeAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DepositeAsset not implemented")
}
func (UnimplementedWalletServiceServer) WithdrawAsset(context.Context, *WithdrawAssetRequest) (*WithdrawAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawAsset not implemented")
}
func (UnimplementedWalletServiceServer) TransferAsset(context.Context, *TransferAssetRequest) (*TransferAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferAsset not implemented")
}
func (UnimplementedWalletServiceServer) ExcahngeAsset(context.Context, *ExchangeAssetRequest) (*ExchangeAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExcahngeAsset not implemented")
}
func (UnimplementedWalletServiceServer) ContextUserWallet(context.Context, *emptypb.Empty) (*ContextUserWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContextUserWallet not implemented")
}
func (UnimplementedWalletServiceServer) ContextUserWalletTransactions(context.Context, *emptypb.Empty) (*ContextUserWalletTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContextUserWalletTransactions not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_DepositeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositeAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DepositeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_DepositeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DepositeAsset(ctx, req.(*DepositeAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_WithdrawAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).WithdrawAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_WithdrawAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).WithdrawAsset(ctx, req.(*WithdrawAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_TransferAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).TransferAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_TransferAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).TransferAsset(ctx, req.(*TransferAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ExcahngeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ExcahngeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ExcahngeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ExcahngeAsset(ctx, req.(*ExchangeAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ContextUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ContextUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ContextUserWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ContextUserWallet(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ContextUserWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ContextUserWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ContextUserWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ContextUserWalletTransactions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositeAsset",
			Handler:    _WalletService_DepositeAsset_Handler,
		},
		{
			MethodName: "WithdrawAsset",
			Handler:    _WalletService_WithdrawAsset_Handler,
		},
		{
			MethodName: "TransferAsset",
			Handler:    _WalletService_TransferAsset_Handler,
		},
		{
			MethodName: "ExcahngeAsset",
			Handler:    _WalletService_ExcahngeAsset_Handler,
		},
		{
			MethodName: "ContextUserWallet",
			Handler:    _WalletService_ContextUserWallet_Handler,
		},
		{
			MethodName: "ContextUserWalletTransactions",
			Handler:    _WalletService_ContextUserWalletTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_wallet_service.proto",
}
