// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_wallet_service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_wallet_service_proto protoreflect.FileDescriptor

const file_rpc_wallet_service_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_wallet_service.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\rrpc_dto.proto2\xa4\x11\n" +
	"\rWalletService\x12\xd2\x01\n" +
	"\fDepositAsset\x12\x1a.proto.DepositAssetRequest\x1a\x1b.proto.DepositAssetResponse\"\x88\x01\x92Ab\n" +
	"\rWalletService\x12\rDeposit Asset\x1a4Deposit asset to authenticated user's wallet accountb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/wallet/deposit_asset\x12\xda\x01\n" +
	"\rWithdrawAsset\x12\x1b.proto.WithdrawAssetRequest\x1a\x1c.proto.WithdrawAssetResponse\"\x8d\x01\x92Af\n" +
	"\rWalletService\x12\x0eWithdraw Asset\x1a7Withdraw asset from authenticated user's wallet accountb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/withdraw_asset\x12\xeb\x01\n" +
	"\rTransferAsset\x12\x1b.proto.TransferAssetRequest\x1a\x1c.proto.TransferAssetResponse\"\x9e\x01\x92Aw\n" +
	"\rWalletService\x12\x0eTransfer Asset\x1aHTransfer asset from authenticated user's wallet to another user's walletb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/transfer_asset\x12\xe4\x01\n" +
	"\rExchangeAsset\x12\x1b.proto.ExchangeAssetRequest\x1a\x1c.proto.ExchangeAssetResponse\"\x97\x01\x92Ap\n" +
	"\rWalletService\x12\x0eExchange Asset\x1aAExchange one asset for another within authenticated user's walletb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/exchange_asset\x12\xff\x01\n" +
	"\x13ContextUserAccounts\x12\x16.google.protobuf.Empty\x1a .proto.ContextUserWalletResponse\"\xad\x01\x92At\n" +
	"\rWalletService\x12\x1dGet Authenticated User Wallet\x1a6Retrieve wallet information for the authenticated userb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\xfa\xb4\x18\f\b\x01\x10x\x1a\x06wallet\x82\xd3\xe4\x93\x02 \x12\x1e/v1/wallet/context_user_wallet\x12\xb3\x02\n" +
	"\x1dContextUserWalletTransactions\x12\x16.google.protobuf.Empty\x1a,.proto.ContextUserWalletTransactionsResponse\"\xcb\x01\x92A\x84\x01\n" +
	"\rWalletService\x12#Get Authenticated User Transactions\x1a@Retrieve transaction history for the authenticated user's walletb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\xfa\xb4\x18\f\b\x01\x10x\x1a\x06wallet\x82\xd3\xe4\x93\x02-\x12+/v1/wallet/context_user_wallet_transactions\x12\xfe\x01\n" +
	"\x13GetAccountTransfers\x12\x16.google.protobuf.Empty\x1a\".proto.GetAccountTransfersResponse\"\xaa\x01\x92A\x7f\n" +
	"\rWalletService\x12\x15Get Account Transfers\x1aIQuery TigerBeetle transfers for a specific account with filtering optionsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\"\x12 /v1/wallet/get_account_transfers\x12\xf1\x01\n" +
	"\x0eQueryTransfers\x12\x1c.proto.QueryTransfersRequest\x1a\x1d.proto.QueryTransfersResponse\"\xa1\x01\x92Ay\n" +
	"\rWalletService\x12\x0fQuery Transfers\x1aIQuery TigerBeetle transfers by metadata, ledger, code, and other criteriab\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/wallet/query_transfers\x12\xde\x01\n" +
	"\x0fLookupTransfers\x12\x1d.proto.LookupTransfersRequest\x1a\x1e.proto.LookupTransfersResponse\"\x8b\x01\x92Ab\n" +
	"\rWalletService\x12\x10Lookup Transfers\x1a1Fetch specific TigerBeetle transfers by their IDsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/wallet/lookup_transfersB\xdb\x02\x92A\x9e\x02\x12\x8a\x01\n" +
	"\x12Wallet Service API\x12:Wallet Service API for user account and wallets management\"1\n" +
	"\x1aWallet Service API Support\x1a\x13liveutil@icloud.com2\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonZY\n" +
	"W\n" +
	"\x06Bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var file_rpc_wallet_service_proto_goTypes = []any{
	(*DepositAssetRequest)(nil),                   // 0: proto.DepositAssetRequest
	(*WithdrawAssetRequest)(nil),                  // 1: proto.WithdrawAssetRequest
	(*TransferAssetRequest)(nil),                  // 2: proto.TransferAssetRequest
	(*ExchangeAssetRequest)(nil),                  // 3: proto.ExchangeAssetRequest
	(*emptypb.Empty)(nil),                         // 4: google.protobuf.Empty
	(*QueryTransfersRequest)(nil),                 // 5: proto.QueryTransfersRequest
	(*LookupTransfersRequest)(nil),                // 6: proto.LookupTransfersRequest
	(*DepositAssetResponse)(nil),                  // 7: proto.DepositAssetResponse
	(*WithdrawAssetResponse)(nil),                 // 8: proto.WithdrawAssetResponse
	(*TransferAssetResponse)(nil),                 // 9: proto.TransferAssetResponse
	(*ExchangeAssetResponse)(nil),                 // 10: proto.ExchangeAssetResponse
	(*ContextUserWalletResponse)(nil),             // 11: proto.ContextUserWalletResponse
	(*ContextUserWalletTransactionsResponse)(nil), // 12: proto.ContextUserWalletTransactionsResponse
	(*GetAccountTransfersResponse)(nil),           // 13: proto.GetAccountTransfersResponse
	(*QueryTransfersResponse)(nil),                // 14: proto.QueryTransfersResponse
	(*LookupTransfersResponse)(nil),               // 15: proto.LookupTransfersResponse
}
var file_rpc_wallet_service_proto_depIdxs = []int32{
	0,  // 0: proto.WalletService.DepositAsset:input_type -> proto.DepositAssetRequest
	1,  // 1: proto.WalletService.WithdrawAsset:input_type -> proto.WithdrawAssetRequest
	2,  // 2: proto.WalletService.TransferAsset:input_type -> proto.TransferAssetRequest
	3,  // 3: proto.WalletService.ExchangeAsset:input_type -> proto.ExchangeAssetRequest
	4,  // 4: proto.WalletService.ContextUserAccounts:input_type -> google.protobuf.Empty
	4,  // 5: proto.WalletService.ContextUserWalletTransactions:input_type -> google.protobuf.Empty
	4,  // 6: proto.WalletService.GetAccountTransfers:input_type -> google.protobuf.Empty
	5,  // 7: proto.WalletService.QueryTransfers:input_type -> proto.QueryTransfersRequest
	6,  // 8: proto.WalletService.LookupTransfers:input_type -> proto.LookupTransfersRequest
	7,  // 9: proto.WalletService.DepositAsset:output_type -> proto.DepositAssetResponse
	8,  // 10: proto.WalletService.WithdrawAsset:output_type -> proto.WithdrawAssetResponse
	9,  // 11: proto.WalletService.TransferAsset:output_type -> proto.TransferAssetResponse
	10, // 12: proto.WalletService.ExchangeAsset:output_type -> proto.ExchangeAssetResponse
	11, // 13: proto.WalletService.ContextUserAccounts:output_type -> proto.ContextUserWalletResponse
	12, // 14: proto.WalletService.ContextUserWalletTransactions:output_type -> proto.ContextUserWalletTransactionsResponse
	13, // 15: proto.WalletService.GetAccountTransfers:output_type -> proto.GetAccountTransfersResponse
	14, // 16: proto.WalletService.QueryTransfers:output_type -> proto.QueryTransfersResponse
	15, // 17: proto.WalletService.LookupTransfers:output_type -> proto.LookupTransfersResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_wallet_service_proto_init() }
func file_rpc_wallet_service_proto_init() {
	if File_rpc_wallet_service_proto != nil {
		return
	}
	file_rpc_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_wallet_service_proto_rawDesc), len(file_rpc_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_wallet_service_proto_goTypes,
		DependencyIndexes: file_rpc_wallet_service_proto_depIdxs,
	}.Build()
	File_rpc_wallet_service_proto = out.File
	file_rpc_wallet_service_proto_goTypes = nil
	file_rpc_wallet_service_proto_depIdxs = nil
}
