// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_wallet_account.model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WalletAccount represents an individual asset account within a wallet.
// Each wallet account is linked to a TigerBeetle ledger account for double-entry bookkeeping.
// Field ordering optimized for Go memory alignment: pointers → bytes → int32 → strings → maps.
type WalletAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the wallet account was created in the system
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 8 bytes (pointer)
	// Timestamp when the wallet account was last updated (null if never updated)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 8 bytes (pointer)
	// Timestamp when the wallet account was soft-deleted (null if active)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // 8 bytes (pointer)
	// TigerBeetle ledger account ID (128-bit, 16 bytes) for double-entry bookkeeping
	// This links the wallet account to its corresponding account in TigerBeetle
	LedgerAccountId []byte `protobuf:"bytes,4,opt,name=ledger_account_id,json=ledgerAccountId,proto3" json:"ledger_account_id,omitempty"` // 16 bytes
	// TigerBeetle account code for categorizing account types (e.g., 1=asset, 2=liability)
	// Stored as int32 for proto3 compatibility (SMALLINT in PostgreSQL)
	LedgerAccountCode int32 `protobuf:"varint,5,opt,name=ledger_account_code,json=ledgerAccountCode,proto3" json:"ledger_account_code,omitempty"` // 4 bytes
	// Unique external identifier for the wallet account (ULID format)
	Identifier string `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// External identifier of the user who owns this wallet account
	UserIdentifier string `protobuf:"bytes,7,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	// External identifier of the parent wallet containing this account
	WalletIdentifier string `protobuf:"bytes,8,opt,name=wallet_identifier,json=walletIdentifier,proto3" json:"wallet_identifier,omitempty"`
	// External identifier of the asset type for this account (e.g., USD, EUR, BTC)
	AssetIdentifier string `protobuf:"bytes,9,opt,name=asset_identifier,json=assetIdentifier,proto3" json:"asset_identifier,omitempty"`
	// Primary Account Number (PAN) for card-based accounts (up to 24 digits)
	// Stored encrypted in the database for PCI-DSS compliance
	PrimaryAccountNumber string `protobuf:"bytes,10,opt,name=primary_account_number,json=primaryAccountNumber,proto3" json:"primary_account_number,omitempty"`
	// International Bank Account Number for bank transfer compatibility (up to 34 characters)
	Iban string `protobuf:"bytes,11,opt,name=iban,proto3" json:"iban,omitempty"`
	// Card Verification Value (CVV) for card security (3-6 digits, encrypted)
	Cvv string `protobuf:"bytes,12,opt,name=cvv,proto3" json:"cvv,omitempty"`
	// Card expiration date in MMYY format (4 characters)
	ExpireDate string `protobuf:"bytes,13,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	// Secondary CVV (CVV2) for additional card security (3-6 digits, encrypted)
	CvvTwo string `protobuf:"bytes,14,opt,name=cvv_two,json=cvvTwo,proto3" json:"cvv_two,omitempty"`
	// Personal Identification Number for account access (encrypted, variable length)
	PinCode string `protobuf:"bytes,15,opt,name=pin_code,json=pinCode,proto3" json:"pin_code,omitempty"`
	// Current lifecycle status of the account (PENDING, ACTIVE, INACTIVE, BANNED, LOCKED, LINKED_LOCKED)
	Status string `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	// Flexible key-value metadata for storing custom attributes (e.g., account limits, preferences)
	MetaData      map[string]string `protobuf:"bytes,17,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAccount) Reset() {
	*x = WalletAccount{}
	mi := &file_rpc_wallet_account_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAccount) ProtoMessage() {}

func (x *WalletAccount) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_account_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAccount.ProtoReflect.Descriptor instead.
func (*WalletAccount) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_account_model_proto_rawDescGZIP(), []int{0}
}

func (x *WalletAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WalletAccount) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *WalletAccount) GetLedgerAccountId() []byte {
	if x != nil {
		return x.LedgerAccountId
	}
	return nil
}

func (x *WalletAccount) GetLedgerAccountCode() int32 {
	if x != nil {
		return x.LedgerAccountCode
	}
	return 0
}

func (x *WalletAccount) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WalletAccount) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

func (x *WalletAccount) GetWalletIdentifier() string {
	if x != nil {
		return x.WalletIdentifier
	}
	return ""
}

func (x *WalletAccount) GetAssetIdentifier() string {
	if x != nil {
		return x.AssetIdentifier
	}
	return ""
}

func (x *WalletAccount) GetPrimaryAccountNumber() string {
	if x != nil {
		return x.PrimaryAccountNumber
	}
	return ""
}

func (x *WalletAccount) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

func (x *WalletAccount) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *WalletAccount) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *WalletAccount) GetCvvTwo() string {
	if x != nil {
		return x.CvvTwo
	}
	return ""
}

func (x *WalletAccount) GetPinCode() string {
	if x != nil {
		return x.PinCode
	}
	return ""
}

func (x *WalletAccount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WalletAccount) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

// WalletAccountResponse is an alias for WalletAccount used in API responses for clarity.
// Maintains backward compatibility with existing API contracts.
type WalletAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the wallet account was created in the system
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the wallet account was last updated (null if never updated)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp when the wallet account was soft-deleted (null if active)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// TigerBeetle ledger account ID (128-bit, 16 bytes) for double-entry bookkeeping
	LedgerAccountId []byte `protobuf:"bytes,4,opt,name=ledger_account_id,json=ledgerAccountId,proto3" json:"ledger_account_id,omitempty"`
	// TigerBeetle account code for categorizing account types
	LedgerAccountCode int32 `protobuf:"varint,5,opt,name=ledger_account_code,json=ledgerAccountCode,proto3" json:"ledger_account_code,omitempty"`
	// Unique external identifier for the wallet account (ULID format)
	Identifier string `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// External identifier of the user who owns this wallet account
	UserIdentifier string `protobuf:"bytes,7,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	// External identifier of the parent wallet containing this account
	WalletIdentifier string `protobuf:"bytes,8,opt,name=wallet_identifier,json=walletIdentifier,proto3" json:"wallet_identifier,omitempty"`
	// External identifier of the asset type for this account
	AssetIdentifier string `protobuf:"bytes,9,opt,name=asset_identifier,json=assetIdentifier,proto3" json:"asset_identifier,omitempty"`
	// Primary Account Number (PAN) for card-based accounts (encrypted)
	PrimaryAccountNumber string `protobuf:"bytes,10,opt,name=primary_account_number,json=primaryAccountNumber,proto3" json:"primary_account_number,omitempty"`
	// International Bank Account Number for bank transfer compatibility
	Iban string `protobuf:"bytes,11,opt,name=iban,proto3" json:"iban,omitempty"`
	// Card Verification Value (CVV) for card security (encrypted)
	Cvv string `protobuf:"bytes,12,opt,name=cvv,proto3" json:"cvv,omitempty"`
	// Card expiration date in MMYY format
	ExpireDate string `protobuf:"bytes,13,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	// Secondary CVV (CVV2) for additional card security (encrypted)
	CvvTwo string `protobuf:"bytes,14,opt,name=cvv_two,json=cvvTwo,proto3" json:"cvv_two,omitempty"`
	// Personal Identification Number for account access (encrypted)
	PinCode string `protobuf:"bytes,15,opt,name=pin_code,json=pinCode,proto3" json:"pin_code,omitempty"`
	// Current lifecycle status of the account
	Status string `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	// Flexible key-value metadata for storing custom attributes
	MetaData      map[string]string `protobuf:"bytes,17,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAccountResponse) Reset() {
	*x = WalletAccountResponse{}
	mi := &file_rpc_wallet_account_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAccountResponse) ProtoMessage() {}

func (x *WalletAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_account_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAccountResponse.ProtoReflect.Descriptor instead.
func (*WalletAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_account_model_proto_rawDescGZIP(), []int{1}
}

func (x *WalletAccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletAccountResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WalletAccountResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *WalletAccountResponse) GetLedgerAccountId() []byte {
	if x != nil {
		return x.LedgerAccountId
	}
	return nil
}

func (x *WalletAccountResponse) GetLedgerAccountCode() int32 {
	if x != nil {
		return x.LedgerAccountCode
	}
	return 0
}

func (x *WalletAccountResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WalletAccountResponse) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

func (x *WalletAccountResponse) GetWalletIdentifier() string {
	if x != nil {
		return x.WalletIdentifier
	}
	return ""
}

func (x *WalletAccountResponse) GetAssetIdentifier() string {
	if x != nil {
		return x.AssetIdentifier
	}
	return ""
}

func (x *WalletAccountResponse) GetPrimaryAccountNumber() string {
	if x != nil {
		return x.PrimaryAccountNumber
	}
	return ""
}

func (x *WalletAccountResponse) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

func (x *WalletAccountResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *WalletAccountResponse) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *WalletAccountResponse) GetCvvTwo() string {
	if x != nil {
		return x.CvvTwo
	}
	return ""
}

func (x *WalletAccountResponse) GetPinCode() string {
	if x != nil {
		return x.PinCode
	}
	return ""
}

func (x *WalletAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WalletAccountResponse) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

var File_rpc_wallet_account_model_proto protoreflect.FileDescriptor

const file_rpc_wallet_account_model_proto_rawDesc = "" +
	"\n" +
	"\x1erpc_wallet_account.model.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x06\n" +
	"\rWalletAccount\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12*\n" +
	"\x11ledger_account_id\x18\x04 \x01(\fR\x0fledgerAccountId\x12.\n" +
	"\x13ledger_account_code\x18\x05 \x01(\x05R\x11ledgerAccountCode\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12'\n" +
	"\x0fuser_identifier\x18\a \x01(\tR\x0euserIdentifier\x12+\n" +
	"\x11wallet_identifier\x18\b \x01(\tR\x10walletIdentifier\x12)\n" +
	"\x10asset_identifier\x18\t \x01(\tR\x0fassetIdentifier\x124\n" +
	"\x16primary_account_number\x18\n" +
	" \x01(\tR\x14primaryAccountNumber\x12\x12\n" +
	"\x04iban\x18\v \x01(\tR\x04iban\x12\x10\n" +
	"\x03cvv\x18\f \x01(\tR\x03cvv\x12\x1f\n" +
	"\vexpire_date\x18\r \x01(\tR\n" +
	"expireDate\x12\x17\n" +
	"\acvv_two\x18\x0e \x01(\tR\x06cvvTwo\x12\x19\n" +
	"\bpin_code\x18\x0f \x01(\tR\apinCode\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12?\n" +
	"\tmeta_data\x18\x11 \x03(\v2\".proto.WalletAccount.MetaDataEntryR\bmetaData\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x06\n" +
	"\x15WalletAccountResponse\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12*\n" +
	"\x11ledger_account_id\x18\x04 \x01(\fR\x0fledgerAccountId\x12.\n" +
	"\x13ledger_account_code\x18\x05 \x01(\x05R\x11ledgerAccountCode\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12'\n" +
	"\x0fuser_identifier\x18\a \x01(\tR\x0euserIdentifier\x12+\n" +
	"\x11wallet_identifier\x18\b \x01(\tR\x10walletIdentifier\x12)\n" +
	"\x10asset_identifier\x18\t \x01(\tR\x0fassetIdentifier\x124\n" +
	"\x16primary_account_number\x18\n" +
	" \x01(\tR\x14primaryAccountNumber\x12\x12\n" +
	"\x04iban\x18\v \x01(\tR\x04iban\x12\x10\n" +
	"\x03cvv\x18\f \x01(\tR\x03cvv\x12\x1f\n" +
	"\vexpire_date\x18\r \x01(\tR\n" +
	"expireDate\x12\x17\n" +
	"\acvv_two\x18\x0e \x01(\tR\x06cvvTwo\x12\x19\n" +
	"\bpin_code\x18\x0f \x01(\tR\apinCode\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12G\n" +
	"\tmeta_data\x18\x11 \x03(\v2*.proto.WalletAccountResponse.MetaDataEntryR\bmetaData\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_wallet_account_model_proto_rawDescOnce sync.Once
	file_rpc_wallet_account_model_proto_rawDescData []byte
)

func file_rpc_wallet_account_model_proto_rawDescGZIP() []byte {
	file_rpc_wallet_account_model_proto_rawDescOnce.Do(func() {
		file_rpc_wallet_account_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_wallet_account_model_proto_rawDesc), len(file_rpc_wallet_account_model_proto_rawDesc)))
	})
	return file_rpc_wallet_account_model_proto_rawDescData
}

var file_rpc_wallet_account_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_wallet_account_model_proto_goTypes = []any{
	(*WalletAccount)(nil),         // 0: proto.WalletAccount
	(*WalletAccountResponse)(nil), // 1: proto.WalletAccountResponse
	nil,                           // 2: proto.WalletAccount.MetaDataEntry
	nil,                           // 3: proto.WalletAccountResponse.MetaDataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_rpc_wallet_account_model_proto_depIdxs = []int32{
	4, // 0: proto.WalletAccount.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: proto.WalletAccount.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: proto.WalletAccount.deleted_at:type_name -> google.protobuf.Timestamp
	2, // 3: proto.WalletAccount.meta_data:type_name -> proto.WalletAccount.MetaDataEntry
	4, // 4: proto.WalletAccountResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: proto.WalletAccountResponse.updated_at:type_name -> google.protobuf.Timestamp
	4, // 6: proto.WalletAccountResponse.deleted_at:type_name -> google.protobuf.Timestamp
	3, // 7: proto.WalletAccountResponse.meta_data:type_name -> proto.WalletAccountResponse.MetaDataEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_rpc_wallet_account_model_proto_init() }
func file_rpc_wallet_account_model_proto_init() {
	if File_rpc_wallet_account_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_wallet_account_model_proto_rawDesc), len(file_rpc_wallet_account_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_wallet_account_model_proto_goTypes,
		DependencyIndexes: file_rpc_wallet_account_model_proto_depIdxs,
		MessageInfos:      file_rpc_wallet_account_model_proto_msgTypes,
	}.Build()
	File_rpc_wallet_account_model_proto = out.File
	file_rpc_wallet_account_model_proto_goTypes = nil
	file_rpc_wallet_account_model_proto_depIdxs = nil
}
