// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_wallet_asset.model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WalletAsset represents a supported asset type (currency or token) in the wallet system.
// Each asset is linked to a TigerBeetle ledger for isolated double-entry bookkeeping.
// Field ordering optimized for Go memory alignment: pointers → int32 → bool → strings → maps.
type WalletAsset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the wallet asset was created in the system
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 8 bytes (pointer)
	// Timestamp when the wallet asset was last updated (null if never updated)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 8 bytes (pointer)
	// Timestamp when the wallet asset was soft-deleted (null if active)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // 8 bytes (pointer)
	// TigerBeetle ledger code for isolating this asset's transactions
	// Each asset type should have a unique ledger for proper accounting separation
	// Stored as int32 for proto3 compatibility (SMALLINT in PostgreSQL)
	LedgerCode int32 `protobuf:"varint,4,opt,name=ledger_code,json=ledgerCode,proto3" json:"ledger_code,omitempty"` // 4 bytes
	// Indicates whether this asset is currently active and available for transactions
	// Inactive assets cannot be used for new transactions but historical data remains
	Active bool `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"` // 1 byte
	// Unique external identifier for the wallet asset (ULID format)
	Identifier string `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Asset code following ISO 4217 for fiat currencies or custom codes for crypto/tokens
	// Examples: "USD", "EUR", "BTC", "ETH", "USDT"
	Code string `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	// Short symbol for display purposes (e.g., "$", "€", "₿")
	// Used in UI for compact representation
	Symbol string `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Human-readable name of the asset (e.g., "US Dollar", "Bitcoin", "Ethereum")
	Title string `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	// Optional description providing additional context about the asset
	// Can include information about decimals, network, contract address, etc.
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// Flexible key-value metadata for storing custom attributes
	// Examples: decimals, contract_address, network, icon_url, min_amount, max_amount
	MetaData      map[string]string `protobuf:"bytes,11,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAsset) Reset() {
	*x = WalletAsset{}
	mi := &file_rpc_wallet_asset_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAsset) ProtoMessage() {}

func (x *WalletAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_asset_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAsset.ProtoReflect.Descriptor instead.
func (*WalletAsset) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_asset_model_proto_rawDescGZIP(), []int{0}
}

func (x *WalletAsset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletAsset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WalletAsset) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *WalletAsset) GetLedgerCode() int32 {
	if x != nil {
		return x.LedgerCode
	}
	return 0
}

func (x *WalletAsset) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *WalletAsset) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WalletAsset) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WalletAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WalletAsset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WalletAsset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WalletAsset) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

// WalletAssetResponse is an alias for WalletAsset used in API responses for clarity.
// Maintains backward compatibility with existing API contracts.
type WalletAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the wallet asset was created in the system
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the wallet asset was last updated (null if never updated)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp when the wallet asset was soft-deleted (null if active)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// TigerBeetle ledger code for isolating this asset's transactions
	LedgerCode int32 `protobuf:"varint,4,opt,name=ledger_code,json=ledgerCode,proto3" json:"ledger_code,omitempty"`
	// Indicates whether this asset is currently active and available for transactions
	Active bool `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// Unique external identifier for the wallet asset (ULID format)
	Identifier string `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Asset code following ISO 4217 or custom codes
	Code string `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	// Short symbol for display purposes
	Symbol string `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Human-readable name of the asset
	Title string `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	// Optional description providing additional context about the asset
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// Flexible key-value metadata for storing custom attributes
	MetaData      map[string]string `protobuf:"bytes,11,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAssetResponse) Reset() {
	*x = WalletAssetResponse{}
	mi := &file_rpc_wallet_asset_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAssetResponse) ProtoMessage() {}

func (x *WalletAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_asset_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAssetResponse.ProtoReflect.Descriptor instead.
func (*WalletAssetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_asset_model_proto_rawDescGZIP(), []int{1}
}

func (x *WalletAssetResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletAssetResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WalletAssetResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *WalletAssetResponse) GetLedgerCode() int32 {
	if x != nil {
		return x.LedgerCode
	}
	return 0
}

func (x *WalletAssetResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *WalletAssetResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WalletAssetResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WalletAssetResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WalletAssetResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WalletAssetResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WalletAssetResponse) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

var File_rpc_wallet_asset_model_proto protoreflect.FileDescriptor

const file_rpc_wallet_asset_model_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_wallet_asset.model.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x03\n" +
	"\vWalletAsset\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1f\n" +
	"\vledger_code\x18\x04 \x01(\x05R\n" +
	"ledgerCode\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12\x16\n" +
	"\x06symbol\x18\b \x01(\tR\x06symbol\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12=\n" +
	"\tmeta_data\x18\v \x03(\v2 .proto.WalletAsset.MetaDataEntryR\bmetaData\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x04\n" +
	"\x13WalletAssetResponse\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1f\n" +
	"\vledger_code\x18\x04 \x01(\x05R\n" +
	"ledgerCode\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12\x16\n" +
	"\x06symbol\x18\b \x01(\tR\x06symbol\x12\x14\n" +
	"\x05title\x18\t \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12E\n" +
	"\tmeta_data\x18\v \x03(\v2(.proto.WalletAssetResponse.MetaDataEntryR\bmetaData\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_wallet_asset_model_proto_rawDescOnce sync.Once
	file_rpc_wallet_asset_model_proto_rawDescData []byte
)

func file_rpc_wallet_asset_model_proto_rawDescGZIP() []byte {
	file_rpc_wallet_asset_model_proto_rawDescOnce.Do(func() {
		file_rpc_wallet_asset_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_wallet_asset_model_proto_rawDesc), len(file_rpc_wallet_asset_model_proto_rawDesc)))
	})
	return file_rpc_wallet_asset_model_proto_rawDescData
}

var file_rpc_wallet_asset_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_wallet_asset_model_proto_goTypes = []any{
	(*WalletAsset)(nil),           // 0: proto.WalletAsset
	(*WalletAssetResponse)(nil),   // 1: proto.WalletAssetResponse
	nil,                           // 2: proto.WalletAsset.MetaDataEntry
	nil,                           // 3: proto.WalletAssetResponse.MetaDataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_rpc_wallet_asset_model_proto_depIdxs = []int32{
	4, // 0: proto.WalletAsset.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: proto.WalletAsset.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: proto.WalletAsset.deleted_at:type_name -> google.protobuf.Timestamp
	2, // 3: proto.WalletAsset.meta_data:type_name -> proto.WalletAsset.MetaDataEntry
	4, // 4: proto.WalletAssetResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: proto.WalletAssetResponse.updated_at:type_name -> google.protobuf.Timestamp
	4, // 6: proto.WalletAssetResponse.deleted_at:type_name -> google.protobuf.Timestamp
	3, // 7: proto.WalletAssetResponse.meta_data:type_name -> proto.WalletAssetResponse.MetaDataEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_rpc_wallet_asset_model_proto_init() }
func file_rpc_wallet_asset_model_proto_init() {
	if File_rpc_wallet_asset_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_wallet_asset_model_proto_rawDesc), len(file_rpc_wallet_asset_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_wallet_asset_model_proto_goTypes,
		DependencyIndexes: file_rpc_wallet_asset_model_proto_depIdxs,
		MessageInfos:      file_rpc_wallet_asset_model_proto_msgTypes,
	}.Build()
	File_rpc_wallet_asset_model_proto = out.File
	file_rpc_wallet_asset_model_proto_goTypes = nil
	file_rpc_wallet_asset_model_proto_depIdxs = nil
}
