// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_wallet_service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_wallet_service_proto protoreflect.FileDescriptor

const file_rpc_wallet_service_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_wallet_service.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\rrpc_dto.proto\x1a\x1brpc_transaction.model.proto2\xbd\n" +
	"\n" +
	"\rWalletService\x12\xbf\x01\n" +
	"\rDepositeAsset\x12\x1b.proto.DepositeAssetRequest\x1a\x1c.proto.DepositeAssetResponse\"s\x92AL\n" +
	"\rWalletService\x12\x0eDeposite Asset\x1a\x1dDeposite asset to user walletb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/deposite_asset\x12\xc1\x01\n" +
	"\rWithdrawAsset\x12\x1b.proto.WithdrawAssetRequest\x1a\x1c.proto.WithdrawAssetResponse\"u\x92AN\n" +
	"\rWalletService\x12\x0eWithdraw Asset\x1a\x1fWithdraw asset from user walletb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/withdraw_asset\x12\xd9\x01\n" +
	"\rTransferAsset\x12\x1b.proto.TransferAssetRequest\x1a\x1c.proto.TransferAssetResponse\"\x8c\x01\x92Ae\n" +
	"\rWalletService\x12\x0eTransfer Asset\x1a6Transfer asset from user wallet to another user walletb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/transfer_asset\x12\xd3\x01\n" +
	"\rExcahngeAsset\x12\x1b.proto.ExchangeAssetRequest\x1a\x1c.proto.ExchangeAssetResponse\"\x86\x01\x92A_\n" +
	"\rWalletService\x12\x0eExchange Asset\x1a0Exchange asset from user wallet to another assetb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wallet/exchange_asset\x12\xd9\x01\n" +
	"\x11ContextUserWallet\x12\x16.google.protobuf.Empty\x1a .proto.ContextUserWalletResponse\"\x89\x01\x92AP\n" +
	"\rWalletService\x12\x13Context User Wallet\x1a\x1cGet context user wallet datab\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\xfa\xb4\x18\f\b\x01\x10x\x1a\x06wallet\x82\xd3\xe4\x93\x02 \x12\x1e/v1/wallet/context_user_wallet\x12\x97\x02\n" +
	"\x1dContextUserWalletTransactions\x12\x16.google.protobuf.Empty\x1a,.proto.ContextUserWalletTransactionsResponse\"\xaf\x01\x92Ai\n" +
	"\rWalletService\x12 Context User Wallet Transactions\x1a(Get context user wallet transaction listb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\xfa\xb4\x18\f\b\x01\x10x\x1a\x06wallet\x82\xd3\xe4\x93\x02-\x12+/v1/wallet/context_user_wallet_transactionsB\xcd\x02\x92A\x90\x02\x12}\n" +
	"\x12Wallet Service API\x12-Wallet Service API for user wallet management\"1\n" +
	"\x1aWallet Service API Support\x1a\x13liveutil@icloud.com2\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonZY\n" +
	"W\n" +
	"\x06Bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var file_rpc_wallet_service_proto_goTypes = []any{
	(*DepositeAssetRequest)(nil),                  // 0: proto.DepositeAssetRequest
	(*WithdrawAssetRequest)(nil),                  // 1: proto.WithdrawAssetRequest
	(*TransferAssetRequest)(nil),                  // 2: proto.TransferAssetRequest
	(*ExchangeAssetRequest)(nil),                  // 3: proto.ExchangeAssetRequest
	(*emptypb.Empty)(nil),                         // 4: google.protobuf.Empty
	(*DepositeAssetResponse)(nil),                 // 5: proto.DepositeAssetResponse
	(*WithdrawAssetResponse)(nil),                 // 6: proto.WithdrawAssetResponse
	(*TransferAssetResponse)(nil),                 // 7: proto.TransferAssetResponse
	(*ExchangeAssetResponse)(nil),                 // 8: proto.ExchangeAssetResponse
	(*ContextUserWalletResponse)(nil),             // 9: proto.ContextUserWalletResponse
	(*ContextUserWalletTransactionsResponse)(nil), // 10: proto.ContextUserWalletTransactionsResponse
}
var file_rpc_wallet_service_proto_depIdxs = []int32{
	0,  // 0: proto.WalletService.DepositeAsset:input_type -> proto.DepositeAssetRequest
	1,  // 1: proto.WalletService.WithdrawAsset:input_type -> proto.WithdrawAssetRequest
	2,  // 2: proto.WalletService.TransferAsset:input_type -> proto.TransferAssetRequest
	3,  // 3: proto.WalletService.ExcahngeAsset:input_type -> proto.ExchangeAssetRequest
	4,  // 4: proto.WalletService.ContextUserWallet:input_type -> google.protobuf.Empty
	4,  // 5: proto.WalletService.ContextUserWalletTransactions:input_type -> google.protobuf.Empty
	5,  // 6: proto.WalletService.DepositeAsset:output_type -> proto.DepositeAssetResponse
	6,  // 7: proto.WalletService.WithdrawAsset:output_type -> proto.WithdrawAssetResponse
	7,  // 8: proto.WalletService.TransferAsset:output_type -> proto.TransferAssetResponse
	8,  // 9: proto.WalletService.ExcahngeAsset:output_type -> proto.ExchangeAssetResponse
	9,  // 10: proto.WalletService.ContextUserWallet:output_type -> proto.ContextUserWalletResponse
	10, // 11: proto.WalletService.ContextUserWalletTransactions:output_type -> proto.ContextUserWalletTransactionsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_wallet_service_proto_init() }
func file_rpc_wallet_service_proto_init() {
	if File_rpc_wallet_service_proto != nil {
		return
	}
	file_rpc_dto_proto_init()
	file_rpc_transaction_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_wallet_service_proto_rawDesc), len(file_rpc_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_wallet_service_proto_goTypes,
		DependencyIndexes: file_rpc_wallet_service_proto_depIdxs,
	}.Build()
	File_rpc_wallet_service_proto = out.File
	file_rpc_wallet_service_proto_goTypes = nil
	file_rpc_wallet_service_proto_depIdxs = nil
}
