// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_dto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// model that contains context user wallet response properties.
type ContextUserWalletResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error sets true if processing failed otherwise sets false
	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// message contains error message if error is true or helper message if error is false
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// wallet data
	Wallet        *Wallet `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUserWalletResponse) Reset() {
	*x = ContextUserWalletResponse{}
	mi := &file_rpc_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUserWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUserWalletResponse) ProtoMessage() {}

func (x *ContextUserWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUserWalletResponse.ProtoReflect.Descriptor instead.
func (*ContextUserWalletResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{0}
}

func (x *ContextUserWalletResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ContextUserWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContextUserWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// model that contains context user transaction list response properties.
type ContextUserWalletTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error sets true if processing failed otherwise sets false
	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// message contains error message if error is true or helper message if error is false
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// transaction list
	Transactions  []*Transaction `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUserWalletTransactionsResponse) Reset() {
	*x = ContextUserWalletTransactionsResponse{}
	mi := &file_rpc_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUserWalletTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUserWalletTransactionsResponse) ProtoMessage() {}

func (x *ContextUserWalletTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUserWalletTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ContextUserWalletTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ContextUserWalletTransactionsResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ContextUserWalletTransactionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContextUserWalletTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// model that contains DepositeAsset request properties.
type DepositeAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset type
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// asset amount
	Amount        float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositeAssetRequest) Reset() {
	*x = DepositeAssetRequest{}
	mi := &file_rpc_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositeAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositeAssetRequest) ProtoMessage() {}

func (x *DepositeAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositeAssetRequest.ProtoReflect.Descriptor instead.
func (*DepositeAssetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{2}
}

func (x *DepositeAssetRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *DepositeAssetRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// model that contains DepositeAsset response properties.
type DepositeAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error sets true if processing failed otherwise sets false
	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// message contains error message if error is true or helper message if error is false
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// transaction data
	Transaction   *Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositeAssetResponse) Reset() {
	*x = DepositeAssetResponse{}
	mi := &file_rpc_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositeAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositeAssetResponse) ProtoMessage() {}

func (x *DepositeAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositeAssetResponse.ProtoReflect.Descriptor instead.
func (*DepositeAssetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{3}
}

func (x *DepositeAssetResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *DepositeAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DepositeAssetResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// model that contains WithdrawAsset request properties.
type WithdrawAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset type
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// asset amount
	Amount        float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawAssetRequest) Reset() {
	*x = WithdrawAssetRequest{}
	mi := &file_rpc_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawAssetRequest) ProtoMessage() {}

func (x *WithdrawAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawAssetRequest.ProtoReflect.Descriptor instead.
func (*WithdrawAssetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawAssetRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *WithdrawAssetRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// model that contains WithdrawAsset response properties.
type WithdrawAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error sets true if processing failed otherwise sets false
	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// message contains error message if error is true or helper message if error is false
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// transaction data
	Transaction   *Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawAssetResponse) Reset() {
	*x = WithdrawAssetResponse{}
	mi := &file_rpc_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawAssetResponse) ProtoMessage() {}

func (x *WithdrawAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawAssetResponse.ProtoReflect.Descriptor instead.
func (*WithdrawAssetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawAssetResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *WithdrawAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WithdrawAssetResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// model that contains TransferAsset request properties.
type TransferAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset type
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// asset amount
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// receiver wallet identifier
	ReceiverWalletIdentifier string `protobuf:"bytes,3,opt,name=receiver_wallet_identifier,json=receiverWalletIdentifier,proto3" json:"receiver_wallet_identifier,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TransferAssetRequest) Reset() {
	*x = TransferAssetRequest{}
	mi := &file_rpc_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAssetRequest) ProtoMessage() {}

func (x *TransferAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAssetRequest.ProtoReflect.Descriptor instead.
func (*TransferAssetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{6}
}

func (x *TransferAssetRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *TransferAssetRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferAssetRequest) GetReceiverWalletIdentifier() string {
	if x != nil {
		return x.ReceiverWalletIdentifier
	}
	return ""
}

// model that contains TransferAsset response properties.
type TransferAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error sets true if processing failed otherwise sets false
	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// message contains error message if error is true or helper message if error is false
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// transaction data
	Transaction   *Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferAssetResponse) Reset() {
	*x = TransferAssetResponse{}
	mi := &file_rpc_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAssetResponse) ProtoMessage() {}

func (x *TransferAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAssetResponse.ProtoReflect.Descriptor instead.
func (*TransferAssetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{7}
}

func (x *TransferAssetResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *TransferAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferAssetResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// model that contains ExchangeAsset request properties.
type ExchangeAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset type
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// asset amount
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// receiver wallet identifier
	ReceiverWalletIdentifier string `protobuf:"bytes,3,opt,name=receiver_wallet_identifier,json=receiverWalletIdentifier,proto3" json:"receiver_wallet_identifier,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExchangeAssetRequest) Reset() {
	*x = ExchangeAssetRequest{}
	mi := &file_rpc_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAssetRequest) ProtoMessage() {}

func (x *ExchangeAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAssetRequest.ProtoReflect.Descriptor instead.
func (*ExchangeAssetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{8}
}

func (x *ExchangeAssetRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ExchangeAssetRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExchangeAssetRequest) GetReceiverWalletIdentifier() string {
	if x != nil {
		return x.ReceiverWalletIdentifier
	}
	return ""
}

// model that contains ExchangeAsset response properties.
type ExchangeAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error sets true if processing failed otherwise sets false
	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// message contains error message if error is true or helper message if error is false
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// transaction data
	Transaction   *Transaction `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAssetResponse) Reset() {
	*x = ExchangeAssetResponse{}
	mi := &file_rpc_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAssetResponse) ProtoMessage() {}

func (x *ExchangeAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAssetResponse.ProtoReflect.Descriptor instead.
func (*ExchangeAssetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_dto_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeAssetResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ExchangeAssetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExchangeAssetResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_rpc_dto_proto protoreflect.FileDescriptor

const file_rpc_dto_proto_rawDesc = "" +
	"\n" +
	"\rrpc_dto.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16rpc_wallet.model.proto\x1a\x1brpc_transaction.model.proto\"r\n" +
	"\x19ContextUserWalletResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x06wallet\x18\x03 \x01(\v2\r.proto.WalletR\x06wallet\"\x8f\x01\n" +
	"%ContextUserWalletTransactionsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\ftransactions\x18\x03 \x03(\v2\x12.proto.TransactionR\ftransactions\"D\n" +
	"\x14DepositeAssetRequest\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\"}\n" +
	"\x15DepositeAssetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\vtransaction\x18\x03 \x01(\v2\x12.proto.TransactionR\vtransaction\"D\n" +
	"\x14WithdrawAssetRequest\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\"}\n" +
	"\x15WithdrawAssetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\vtransaction\x18\x03 \x01(\v2\x12.proto.TransactionR\vtransaction\"\x82\x01\n" +
	"\x14TransferAssetRequest\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12<\n" +
	"\x1areceiver_wallet_identifier\x18\x03 \x01(\tR\x18receiverWalletIdentifier\"}\n" +
	"\x15TransferAssetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\vtransaction\x18\x03 \x01(\v2\x12.proto.TransactionR\vtransaction\"\x82\x01\n" +
	"\x14ExchangeAssetRequest\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12<\n" +
	"\x1areceiver_wallet_identifier\x18\x03 \x01(\tR\x18receiverWalletIdentifier\"}\n" +
	"\x15ExchangeAssetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\vtransaction\x18\x03 \x01(\v2\x12.proto.TransactionR\vtransactionB9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_dto_proto_rawDescOnce sync.Once
	file_rpc_dto_proto_rawDescData []byte
)

func file_rpc_dto_proto_rawDescGZIP() []byte {
	file_rpc_dto_proto_rawDescOnce.Do(func() {
		file_rpc_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_dto_proto_rawDesc), len(file_rpc_dto_proto_rawDesc)))
	})
	return file_rpc_dto_proto_rawDescData
}

var file_rpc_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_dto_proto_goTypes = []any{
	(*ContextUserWalletResponse)(nil),             // 0: proto.ContextUserWalletResponse
	(*ContextUserWalletTransactionsResponse)(nil), // 1: proto.ContextUserWalletTransactionsResponse
	(*DepositeAssetRequest)(nil),                  // 2: proto.DepositeAssetRequest
	(*DepositeAssetResponse)(nil),                 // 3: proto.DepositeAssetResponse
	(*WithdrawAssetRequest)(nil),                  // 4: proto.WithdrawAssetRequest
	(*WithdrawAssetResponse)(nil),                 // 5: proto.WithdrawAssetResponse
	(*TransferAssetRequest)(nil),                  // 6: proto.TransferAssetRequest
	(*TransferAssetResponse)(nil),                 // 7: proto.TransferAssetResponse
	(*ExchangeAssetRequest)(nil),                  // 8: proto.ExchangeAssetRequest
	(*ExchangeAssetResponse)(nil),                 // 9: proto.ExchangeAssetResponse
	(*Wallet)(nil),                                // 10: proto.Wallet
	(*Transaction)(nil),                           // 11: proto.Transaction
}
var file_rpc_dto_proto_depIdxs = []int32{
	10, // 0: proto.ContextUserWalletResponse.wallet:type_name -> proto.Wallet
	11, // 1: proto.ContextUserWalletTransactionsResponse.transactions:type_name -> proto.Transaction
	11, // 2: proto.DepositeAssetResponse.transaction:type_name -> proto.Transaction
	11, // 3: proto.WithdrawAssetResponse.transaction:type_name -> proto.Transaction
	11, // 4: proto.TransferAssetResponse.transaction:type_name -> proto.Transaction
	11, // 5: proto.ExchangeAssetResponse.transaction:type_name -> proto.Transaction
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_dto_proto_init() }
func file_rpc_dto_proto_init() {
	if File_rpc_dto_proto != nil {
		return
	}
	file_rpc_wallet_model_proto_init()
	file_rpc_transaction_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_dto_proto_rawDesc), len(file_rpc_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_dto_proto_goTypes,
		DependencyIndexes: file_rpc_dto_proto_depIdxs,
		MessageInfos:      file_rpc_dto_proto_msgTypes,
	}.Build()
	File_rpc_dto_proto = out.File
	file_rpc_dto_proto_goTypes = nil
	file_rpc_dto_proto_depIdxs = nil
}
