// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_wallet.model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wallet represents a user's wallet container that holds multiple asset accounts.
// A wallet is the top-level entity that groups related wallet accounts for a single user.
// Field ordering optimized for Go memory alignment: pointers/timestamps → bools → strings → maps.
type Wallet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the wallet was created in the system
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 8 bytes (pointer)
	// Timestamp when the wallet was last updated (null if never updated)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 8 bytes (pointer)
	// Timestamp when the wallet was soft-deleted (null if active)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // 8 bytes (pointer)
	// Expiration timestamp for temporary or time-limited wallets (null if permanent)
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 8 bytes (pointer)
	// Indicates whether the wallet is banned due to policy violations or fraud
	Banned bool `protobuf:"varint,5,opt,name=banned,proto3" json:"banned,omitempty"` // 1 byte
	// Unique external identifier for the wallet (ULID format for sortable, globally unique IDs)
	Identifier string `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Human-readable name or label for the wallet (e.g., "Main Wallet", "Savings")
	Title string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	// Optional description providing additional context about the wallet's purpose
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Current lifecycle status of the wallet (PENDING, ISSUED, ACTIVE)
	Status string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	// External identifier of the user who owns this wallet
	UserIdentifier string `protobuf:"bytes,10,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	// External identifier of the primary/base asset for this wallet (e.g., default currency)
	AssetIdentifier string `protobuf:"bytes,11,opt,name=asset_identifier,json=assetIdentifier,proto3" json:"asset_identifier,omitempty"`
	// Flexible key-value metadata for storing custom attributes (e.g., tags, categories, limits)
	MetaData map[string]string `protobuf:"bytes,12,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Asset of wallet
	Asset *Asset `protobuf:"bytes,13,opt,name=asset,proto3" json:"asset,omitempty"`
	// Balance of wallet
	Balance       *WalletBalance `protobuf:"bytes,14,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_rpc_wallet_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_model_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Wallet) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Wallet) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Wallet) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *Wallet) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Wallet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Wallet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Wallet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Wallet) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

func (x *Wallet) GetAssetIdentifier() string {
	if x != nil {
		return x.AssetIdentifier
	}
	return ""
}

func (x *Wallet) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Wallet) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Wallet) GetBalance() *WalletBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

// WalletBalance represents the balance of a wallet.
type WalletBalance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Credit balance of wallet
	Credit string `protobuf:"bytes,1,opt,name=credit,proto3" json:"credit,omitempty"`
	// Debit balance of wallet
	Debit string `protobuf:"bytes,2,opt,name=debit,proto3" json:"debit,omitempty"`
	// Pending credit balance of wallet
	PendingCredit string `protobuf:"bytes,3,opt,name=pending_credit,json=pendingCredit,proto3" json:"pending_credit,omitempty"`
	// Pending debit balance of wallet
	PendingDebit string `protobuf:"bytes,4,opt,name=pending_debit,json=pendingDebit,proto3" json:"pending_debit,omitempty"`
	// Total balance of wallet
	Balance string `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	// Pending balance of wallet
	Pending       string `protobuf:"bytes,6,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletBalance) Reset() {
	*x = WalletBalance{}
	mi := &file_rpc_wallet_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalance) ProtoMessage() {}

func (x *WalletBalance) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalance.ProtoReflect.Descriptor instead.
func (*WalletBalance) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_model_proto_rawDescGZIP(), []int{1}
}

func (x *WalletBalance) GetCredit() string {
	if x != nil {
		return x.Credit
	}
	return ""
}

func (x *WalletBalance) GetDebit() string {
	if x != nil {
		return x.Debit
	}
	return ""
}

func (x *WalletBalance) GetPendingCredit() string {
	if x != nil {
		return x.PendingCredit
	}
	return ""
}

func (x *WalletBalance) GetPendingDebit() string {
	if x != nil {
		return x.PendingDebit
	}
	return ""
}

func (x *WalletBalance) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *WalletBalance) GetPending() string {
	if x != nil {
		return x.Pending
	}
	return ""
}

// WalletResponse is an alias for Wallet used in API responses for clarity.
// Maintains backward compatibility with existing API contracts.
type WalletResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the wallet was created in the system
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when the wallet was last updated (null if never updated)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp when the wallet was soft-deleted (null if active)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Expiration timestamp for temporary or time-limited wallets (null if permanent)
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Indicates whether the wallet is banned due to policy violations or fraud
	Banned bool `protobuf:"varint,5,opt,name=banned,proto3" json:"banned,omitempty"`
	// Unique external identifier for the wallet (ULID format)
	Identifier string `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Human-readable name or label for the wallet
	Title string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	// Optional description providing additional context about the wallet's purpose
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Current lifecycle status of the wallet (PENDING, ISSUED, ACTIVE)
	Status string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	// External identifier of the user who owns this wallet
	UserIdentifier string `protobuf:"bytes,10,opt,name=user_identifier,json=userIdentifier,proto3" json:"user_identifier,omitempty"`
	// External identifier of the primary/base asset for this wallet
	BaseAssetIdentifier string `protobuf:"bytes,11,opt,name=base_asset_identifier,json=baseAssetIdentifier,proto3" json:"base_asset_identifier,omitempty"`
	// Flexible key-value metadata for storing custom attributes
	MetaData      map[string]string `protobuf:"bytes,12,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_rpc_wallet_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_wallet_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_rpc_wallet_model_proto_rawDescGZIP(), []int{2}
}

func (x *WalletResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WalletResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WalletResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *WalletResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *WalletResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *WalletResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WalletResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WalletResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WalletResponse) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

func (x *WalletResponse) GetBaseAssetIdentifier() string {
	if x != nil {
		return x.BaseAssetIdentifier
	}
	return ""
}

func (x *WalletResponse) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

var File_rpc_wallet_model_proto protoreflect.FileDescriptor

const file_rpc_wallet_model_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_wallet.model.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15rpc_asset.model.proto\"\x9b\x05\n" +
	"\x06Wallet\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06banned\x18\x05 \x01(\bR\x06banned\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12'\n" +
	"\x0fuser_identifier\x18\n" +
	" \x01(\tR\x0euserIdentifier\x12)\n" +
	"\x10asset_identifier\x18\v \x01(\tR\x0fassetIdentifier\x128\n" +
	"\tmeta_data\x18\f \x03(\v2\x1b.proto.Wallet.MetaDataEntryR\bmetaData\x12\"\n" +
	"\x05asset\x18\r \x01(\v2\f.proto.AssetR\x05asset\x12.\n" +
	"\abalance\x18\x0e \x01(\v2\x14.proto.WalletBalanceR\abalance\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\rWalletBalance\x12\x16\n" +
	"\x06credit\x18\x01 \x01(\tR\x06credit\x12\x14\n" +
	"\x05debit\x18\x02 \x01(\tR\x05debit\x12%\n" +
	"\x0epending_credit\x18\x03 \x01(\tR\rpendingCredit\x12#\n" +
	"\rpending_debit\x18\x04 \x01(\tR\fpendingDebit\x12\x18\n" +
	"\abalance\x18\x05 \x01(\tR\abalance\x12\x18\n" +
	"\apending\x18\x06 \x01(\tR\apending\"\xe0\x04\n" +
	"\x0eWalletResponse\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06banned\x18\x05 \x01(\bR\x06banned\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12'\n" +
	"\x0fuser_identifier\x18\n" +
	" \x01(\tR\x0euserIdentifier\x122\n" +
	"\x15base_asset_identifier\x18\v \x01(\tR\x13baseAssetIdentifier\x12@\n" +
	"\tmeta_data\x18\f \x03(\v2#.proto.WalletResponse.MetaDataEntryR\bmetaData\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_wallet_model_proto_rawDescOnce sync.Once
	file_rpc_wallet_model_proto_rawDescData []byte
)

func file_rpc_wallet_model_proto_rawDescGZIP() []byte {
	file_rpc_wallet_model_proto_rawDescOnce.Do(func() {
		file_rpc_wallet_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_wallet_model_proto_rawDesc), len(file_rpc_wallet_model_proto_rawDesc)))
	})
	return file_rpc_wallet_model_proto_rawDescData
}

var file_rpc_wallet_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_wallet_model_proto_goTypes = []any{
	(*Wallet)(nil),                // 0: proto.Wallet
	(*WalletBalance)(nil),         // 1: proto.WalletBalance
	(*WalletResponse)(nil),        // 2: proto.WalletResponse
	nil,                           // 3: proto.Wallet.MetaDataEntry
	nil,                           // 4: proto.WalletResponse.MetaDataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*Asset)(nil),                 // 6: proto.Asset
}
var file_rpc_wallet_model_proto_depIdxs = []int32{
	5,  // 0: proto.Wallet.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: proto.Wallet.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: proto.Wallet.deleted_at:type_name -> google.protobuf.Timestamp
	5,  // 3: proto.Wallet.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 4: proto.Wallet.meta_data:type_name -> proto.Wallet.MetaDataEntry
	6,  // 5: proto.Wallet.asset:type_name -> proto.Asset
	1,  // 6: proto.Wallet.balance:type_name -> proto.WalletBalance
	5,  // 7: proto.WalletResponse.created_at:type_name -> google.protobuf.Timestamp
	5,  // 8: proto.WalletResponse.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 9: proto.WalletResponse.deleted_at:type_name -> google.protobuf.Timestamp
	5,  // 10: proto.WalletResponse.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 11: proto.WalletResponse.meta_data:type_name -> proto.WalletResponse.MetaDataEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rpc_wallet_model_proto_init() }
func file_rpc_wallet_model_proto_init() {
	if File_rpc_wallet_model_proto != nil {
		return
	}
	file_rpc_asset_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_wallet_model_proto_rawDesc), len(file_rpc_wallet_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_wallet_model_proto_goTypes,
		DependencyIndexes: file_rpc_wallet_model_proto_depIdxs,
		MessageInfos:      file_rpc_wallet_model_proto_msgTypes,
	}.Build()
	File_rpc_wallet_model_proto = out.File
	file_rpc_wallet_model_proto_goTypes = nil
	file_rpc_wallet_model_proto_depIdxs = nil
}
