// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_transaction.model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction message containing all transaction data and nested entities
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transaction public identifier to hide real database id of transaction
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// transaction type
	TransactionType string `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	// transaction asset type
	Asset string `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	// transaction amount
	Amount float32 `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// transaction fee
	Fee float32 `protobuf:"fixed32,5,opt,name=fee,proto3" json:"fee,omitempty"`
	// transaction status
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// transaction creation time
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_rpc_transaction_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transaction_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_rpc_transaction_model_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Transaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *Transaction) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Transaction) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetFee() float32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_rpc_transaction_model_proto protoreflect.FileDescriptor

const file_rpc_transaction_model_proto_rawDesc = "" +
	"\n" +
	"\x1brpc_transaction.model.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\vTransaction\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12)\n" +
	"\x10transaction_type\x18\x02 \x01(\tR\x0ftransactionType\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x02R\x03fee\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_transaction_model_proto_rawDescOnce sync.Once
	file_rpc_transaction_model_proto_rawDescData []byte
)

func file_rpc_transaction_model_proto_rawDescGZIP() []byte {
	file_rpc_transaction_model_proto_rawDescOnce.Do(func() {
		file_rpc_transaction_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_transaction_model_proto_rawDesc), len(file_rpc_transaction_model_proto_rawDesc)))
	})
	return file_rpc_transaction_model_proto_rawDescData
}

var file_rpc_transaction_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_transaction_model_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: proto.Transaction
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_rpc_transaction_model_proto_depIdxs = []int32{
	1, // 0: proto.Transaction.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_transaction_model_proto_init() }
func file_rpc_transaction_model_proto_init() {
	if File_rpc_transaction_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_transaction_model_proto_rawDesc), len(file_rpc_transaction_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_transaction_model_proto_goTypes,
		DependencyIndexes: file_rpc_transaction_model_proto_depIdxs,
		MessageInfos:      file_rpc_transaction_model_proto_msgTypes,
	}.Build()
	File_rpc_transaction_model_proto = out.File
	file_rpc_transaction_model_proto_goTypes = nil
	file_rpc_transaction_model_proto_depIdxs = nil
}
