// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rpc_asset.model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique external identifier for the asset (ULID format)
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Asset code following ISO 4217 for fiat currencies or custom codes for crypto/tokens
	// Examples: "USD", "EUR", "BTC", "ETH", "USDT"
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Short symbol for display purposes
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Human-readable name of the asset
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Optional description providing additional context about the asset
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Asset unit
	Unit string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	// Asset unit title
	UnitTitle string `protobuf:"bytes,7,opt,name=unit_title,json=unitTitle,proto3" json:"unit_title,omitempty"`
	// Asset decimals
	Decimals int32 `protobuf:"varint,8,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// Asset network
	Network string `protobuf:"bytes,9,opt,name=network,proto3" json:"network,omitempty"`
	// Asset icon url
	IconUrl string `protobuf:"bytes,10,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// Flexible key-value metadata for storing custom attributes
	MetaData map[string]string `protobuf:"bytes,11,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ledger code of asset
	LedgerCode    int32 `protobuf:"varint,12,opt,name=ledger_code,json=ledgerCode,proto3" json:"ledger_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_rpc_asset_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_asset_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_rpc_asset_model_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Asset) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Asset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Asset) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Asset) GetUnitTitle() string {
	if x != nil {
		return x.UnitTitle
	}
	return ""
}

func (x *Asset) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Asset) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Asset) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Asset) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Asset) GetLedgerCode() int32 {
	if x != nil {
		return x.LedgerCode
	}
	return 0
}

var File_rpc_asset_model_proto protoreflect.FileDescriptor

const file_rpc_asset_model_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_asset.model.proto\x12\x05proto\"\xa6\x03\n" +
	"\x05Asset\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"unit_title\x18\a \x01(\tR\tunitTitle\x12\x1a\n" +
	"\bdecimals\x18\b \x01(\x05R\bdecimals\x12\x18\n" +
	"\anetwork\x18\t \x01(\tR\anetwork\x12\x19\n" +
	"\bicon_url\x18\n" +
	" \x01(\tR\aiconUrl\x127\n" +
	"\tmeta_data\x18\v \x03(\v2\x1a.proto.Asset.MetaDataEntryR\bmetaData\x12\x1f\n" +
	"\vledger_code\x18\f \x01(\x05R\n" +
	"ledgerCode\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/liveutil/wallet-service/internal/abstract/pbb\x06proto3"

var (
	file_rpc_asset_model_proto_rawDescOnce sync.Once
	file_rpc_asset_model_proto_rawDescData []byte
)

func file_rpc_asset_model_proto_rawDescGZIP() []byte {
	file_rpc_asset_model_proto_rawDescOnce.Do(func() {
		file_rpc_asset_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_asset_model_proto_rawDesc), len(file_rpc_asset_model_proto_rawDesc)))
	})
	return file_rpc_asset_model_proto_rawDescData
}

var file_rpc_asset_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_asset_model_proto_goTypes = []any{
	(*Asset)(nil), // 0: proto.Asset
	nil,           // 1: proto.Asset.MetaDataEntry
}
var file_rpc_asset_model_proto_depIdxs = []int32{
	1, // 0: proto.Asset.meta_data:type_name -> proto.Asset.MetaDataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_asset_model_proto_init() }
func file_rpc_asset_model_proto_init() {
	if File_rpc_asset_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_asset_model_proto_rawDesc), len(file_rpc_asset_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_asset_model_proto_goTypes,
		DependencyIndexes: file_rpc_asset_model_proto_depIdxs,
		MessageInfos:      file_rpc_asset_model_proto_msgTypes,
	}.Build()
	File_rpc_asset_model_proto = out.File
	file_rpc_asset_model_proto_goTypes = nil
	file_rpc_asset_model_proto_depIdxs = nil
}
