// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  title,
  description,
  status,
  banned,
  user_identifier,
  base_asset_identifier,
  meta_data,
  expires_at,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP, NULL
)
RETURNING identifier, title, description, status, banned, user_identifier, base_asset_identifier, meta_data, expires_at, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	Status              AccountStatus      `json:"status"`
	Banned              bool               `json:"banned"`
	UserIdentifier      ulid.ULID          `json:"user_identifier"`
	BaseAssetIdentifier ulid.ULID          `json:"base_asset_identifier"`
	MetaData            []byte             `json:"meta_data"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Banned,
		arg.UserIdentifier,
		arg.BaseAssetIdentifier,
		arg.MetaData,
		arg.ExpiresAt,
	)
	var i Account
	err := row.Scan(
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Banned,
		&i.UserIdentifier,
		&i.BaseAssetIdentifier,
		&i.MetaData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByIdentifier = `-- name: GetAccountByIdentifier :one
SELECT identifier, title, description, status, banned, user_identifier, base_asset_identifier, meta_data, expires_at, created_at, updated_at, deleted_at FROM accounts
WHERE identifier = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAccountByIdentifier(ctx context.Context, identifier ulid.ULID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIdentifier, identifier)
	var i Account
	err := row.Scan(
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Banned,
		&i.UserIdentifier,
		&i.BaseAssetIdentifier,
		&i.MetaData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT identifier, title, description, status, banned, user_identifier, base_asset_identifier, meta_data, expires_at, created_at, updated_at, deleted_at FROM accounts
WHERE user_identifier = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserAccountsParams struct {
	UserIdentifier ulid.ULID `json:"user_identifier"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) GetUserAccounts(ctx context.Context, arg GetUserAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, getUserAccounts, arg.UserIdentifier, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Identifier,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Banned,
			&i.UserIdentifier,
			&i.BaseAssetIdentifier,
			&i.MetaData,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
