// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  title,
  description,
  status,
  banned,
  user_identifier,
  base_asset_identifier,
  meta_data,
  expires_at,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, CURRENT_TIMESTAMP, NULL
)
RETURNING id, identifier, title, description, status, banned, user_identifier, base_asset_identifier, meta_data, expires_at, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	Status              AccountStatus      `json:"status"`
	Banned              bool               `json:"banned"`
	UserIdentifier      string             `json:"user_identifier"`
	BaseAssetIdentifier string             `json:"base_asset_identifier"`
	MetaData            []byte             `json:"meta_data"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Banned,
		arg.UserIdentifier,
		arg.BaseAssetIdentifier,
		arg.MetaData,
		arg.ExpiresAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Banned,
		&i.UserIdentifier,
		&i.BaseAssetIdentifier,
		&i.MetaData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByIdentifier = `-- name: GetAccountByIdentifier :one
SELECT id, identifier, title, description, status, banned, user_identifier, base_asset_identifier, meta_data, expires_at, created_at, updated_at, deleted_at FROM accounts
WHERE identifier::varchar(32) = $1::varchar(32)
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAccountByIdentifier(ctx context.Context, dollar_1 string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIdentifier, dollar_1)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Banned,
		&i.UserIdentifier,
		&i.BaseAssetIdentifier,
		&i.MetaData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAccount = `-- name: GetUserAccount :one
SELECT id, identifier, title, description, status, banned, user_identifier, base_asset_identifier, meta_data, expires_at, created_at, updated_at, deleted_at FROM accounts
WHERE accounts.user_identifier = $1
LIMIT 1
`

func (q *Queries) GetUserAccount(ctx context.Context, userIdentifier string) (Account, error) {
	row := q.db.QueryRow(ctx, getUserAccount, userIdentifier)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Banned,
		&i.UserIdentifier,
		&i.BaseAssetIdentifier,
		&i.MetaData,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
