// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package repository

import (
	"context"
)

const getAllWalletAssets = `-- name: GetAllWalletAssets :many
SELECT id, identifier, active, code, symbol, title, description, predefined, unit, unit_title, decimals, network, icon_url, meta_data, ledger_code, created_at, updated_at, deleted_at FROM wallet_assets
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllWalletAssetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllWalletAssets(ctx context.Context, arg GetAllWalletAssetsParams) ([]WalletAsset, error) {
	rows, err := q.db.Query(ctx, getAllWalletAssets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletAsset{}
	for rows.Next() {
		var i WalletAsset
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.Active,
			&i.Code,
			&i.Symbol,
			&i.Title,
			&i.Description,
			&i.Predefined,
			&i.Unit,
			&i.UnitTitle,
			&i.Decimals,
			&i.Network,
			&i.IconUrl,
			&i.MetaData,
			&i.LedgerCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletAssetByIdentifier = `-- name: GetWalletAssetByIdentifier :one
SELECT id, identifier, active, code, symbol, title, description, predefined, unit, unit_title, decimals, network, icon_url, meta_data, ledger_code, created_at, updated_at, deleted_at FROM wallet_assets
WHERE identifier::text = $1::text
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWalletAssetByIdentifier(ctx context.Context, dollar_1 string) (WalletAsset, error) {
	row := q.db.QueryRow(ctx, getWalletAssetByIdentifier, dollar_1)
	var i WalletAsset
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Active,
		&i.Code,
		&i.Symbol,
		&i.Title,
		&i.Description,
		&i.Predefined,
		&i.Unit,
		&i.UnitTitle,
		&i.Decimals,
		&i.Network,
		&i.IconUrl,
		&i.MetaData,
		&i.LedgerCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletAssetBySymbol = `-- name: GetWalletAssetBySymbol :one
SELECT id, identifier, active, code, symbol, title, description, predefined, unit, unit_title, decimals, network, icon_url, meta_data, ledger_code, created_at, updated_at, deleted_at FROM wallet_assets
WHERE symbol = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWalletAssetBySymbol(ctx context.Context, symbol string) (WalletAsset, error) {
	row := q.db.QueryRow(ctx, getWalletAssetBySymbol, symbol)
	var i WalletAsset
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Active,
		&i.Code,
		&i.Symbol,
		&i.Title,
		&i.Description,
		&i.Predefined,
		&i.Unit,
		&i.UnitTitle,
		&i.Decimals,
		&i.Network,
		&i.IconUrl,
		&i.MetaData,
		&i.LedgerCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
