// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletCard = `-- name: CreateWalletCard :one
INSERT INTO wallet_cards (
    wallet_id,
    wallet_identifier,
    user_identifier,
    card_product_id,
    issuer_bin,
    brand,
    pan_fingerprint,
    masked_pan,
    pan_last4,
    expiry_month,
    expiry_year,
    cardholder_name,
    service_code,
    cvv_digest,
    cvv_two_digest,
    track1_digest,
    track2_digest,
    pin_digest,
    last_authenticated_at,
    status,
    meta_data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
RETURNING id, identifier, wallet_id, wallet_identifier, user_identifier, card_product_id, issuer_bin, brand, pan_fingerprint, masked_pan, pan_last4, expiry_month, expiry_year, cardholder_name, service_code, cvv_digest, cvv_two_digest, track1_digest, track2_digest, pin_digest, last_authenticated_at, status, meta_data, created_at, updated_at, deleted_at
`

type CreateWalletCardParams struct {
	WalletID            int64              `json:"wallet_id"`
	WalletIdentifier    string             `json:"wallet_identifier"`
	UserIdentifier      string             `json:"user_identifier"`
	CardProductID       int64              `json:"card_product_id"`
	IssuerBin           string             `json:"issuer_bin"`
	Brand               CardNetwork        `json:"brand"`
	PanFingerprint      string             `json:"pan_fingerprint"`
	MaskedPan           string             `json:"masked_pan"`
	PanLast4            string             `json:"pan_last4"`
	ExpiryMonth         int32              `json:"expiry_month"`
	ExpiryYear          int32              `json:"expiry_year"`
	CardholderName      string             `json:"cardholder_name"`
	ServiceCode         string             `json:"service_code"`
	CvvDigest           string             `json:"cvv_digest"`
	CvvTwoDigest        string             `json:"cvv_two_digest"`
	Track1Digest        pgtype.Text        `json:"track1_digest"`
	Track2Digest        string             `json:"track2_digest"`
	PinDigest           pgtype.Text        `json:"pin_digest"`
	LastAuthenticatedAt pgtype.Timestamptz `json:"last_authenticated_at"`
	Status              WalletCardStatus   `json:"status"`
	MetaData            []byte             `json:"meta_data"`
}

func (q *Queries) CreateWalletCard(ctx context.Context, arg CreateWalletCardParams) (WalletCard, error) {
	row := q.db.QueryRow(ctx, createWalletCard,
		arg.WalletID,
		arg.WalletIdentifier,
		arg.UserIdentifier,
		arg.CardProductID,
		arg.IssuerBin,
		arg.Brand,
		arg.PanFingerprint,
		arg.MaskedPan,
		arg.PanLast4,
		arg.ExpiryMonth,
		arg.ExpiryYear,
		arg.CardholderName,
		arg.ServiceCode,
		arg.CvvDigest,
		arg.CvvTwoDigest,
		arg.Track1Digest,
		arg.Track2Digest,
		arg.PinDigest,
		arg.LastAuthenticatedAt,
		arg.Status,
		arg.MetaData,
	)
	var i WalletCard
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.WalletID,
		&i.WalletIdentifier,
		&i.UserIdentifier,
		&i.CardProductID,
		&i.IssuerBin,
		&i.Brand,
		&i.PanFingerprint,
		&i.MaskedPan,
		&i.PanLast4,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.CardholderName,
		&i.ServiceCode,
		&i.CvvDigest,
		&i.CvvTwoDigest,
		&i.Track1Digest,
		&i.Track2Digest,
		&i.PinDigest,
		&i.LastAuthenticatedAt,
		&i.Status,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWalletCardEvent = `-- name: CreateWalletCardEvent :one
INSERT INTO wallet_card_events (
    wallet_card_id,
    wallet_card_identifier,
    user_identifier,
    event_type,
    success,
    remote_ip,
    meta_data,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    CURRENT_TIMESTAMP
)
RETURNING id, identifier, wallet_card_id, wallet_card_identifier, user_identifier, event_type, success, remote_ip, meta_data, created_at
`

type CreateWalletCardEventParams struct {
	WalletCardID         int64               `json:"wallet_card_id"`
	WalletCardIdentifier string              `json:"wallet_card_identifier"`
	UserIdentifier       string              `json:"user_identifier"`
	EventType            WalletCardEventType `json:"event_type"`
	Success              bool                `json:"success"`
	RemoteIp             pgtype.Text         `json:"remote_ip"`
	MetaData             []byte              `json:"meta_data"`
}

func (q *Queries) CreateWalletCardEvent(ctx context.Context, arg CreateWalletCardEventParams) (WalletCardEvent, error) {
	row := q.db.QueryRow(ctx, createWalletCardEvent,
		arg.WalletCardID,
		arg.WalletCardIdentifier,
		arg.UserIdentifier,
		arg.EventType,
		arg.Success,
		arg.RemoteIp,
		arg.MetaData,
	)
	var i WalletCardEvent
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.WalletCardID,
		&i.WalletCardIdentifier,
		&i.UserIdentifier,
		&i.EventType,
		&i.Success,
		&i.RemoteIp,
		&i.MetaData,
		&i.CreatedAt,
	)
	return i, err
}

const ensureCardProduct = `-- name: EnsureCardProduct :one
INSERT INTO card_products (
    issuer_bin_id,
    name,
    pan_length,
    cvv_length,
    expiry_months,
    service_code,
    allow_magnetic_stripe,
    meta_data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (name) DO UPDATE SET
    issuer_bin_id = EXCLUDED.issuer_bin_id,
    pan_length = EXCLUDED.pan_length,
    cvv_length = EXCLUDED.cvv_length,
    expiry_months = EXCLUDED.expiry_months,
    service_code = EXCLUDED.service_code,
    allow_magnetic_stripe = EXCLUDED.allow_magnetic_stripe,
    meta_data = EXCLUDED.meta_data,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, identifier, issuer_bin_id, name, pan_length, cvv_length, expiry_months, service_code, allow_magnetic_stripe, meta_data, created_at, updated_at, deleted_at
`

type EnsureCardProductParams struct {
	IssuerBinID         int64  `json:"issuer_bin_id"`
	Name                string `json:"name"`
	PanLength           int32  `json:"pan_length"`
	CvvLength           int32  `json:"cvv_length"`
	ExpiryMonths        int32  `json:"expiry_months"`
	ServiceCode         string `json:"service_code"`
	AllowMagneticStripe bool   `json:"allow_magnetic_stripe"`
	MetaData            []byte `json:"meta_data"`
}

func (q *Queries) EnsureCardProduct(ctx context.Context, arg EnsureCardProductParams) (CardProduct, error) {
	row := q.db.QueryRow(ctx, ensureCardProduct,
		arg.IssuerBinID,
		arg.Name,
		arg.PanLength,
		arg.CvvLength,
		arg.ExpiryMonths,
		arg.ServiceCode,
		arg.AllowMagneticStripe,
		arg.MetaData,
	)
	var i CardProduct
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.IssuerBinID,
		&i.Name,
		&i.PanLength,
		&i.CvvLength,
		&i.ExpiryMonths,
		&i.ServiceCode,
		&i.AllowMagneticStripe,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ensureIssuerBin = `-- name: EnsureIssuerBin :one
INSERT INTO issuer_bins (
    active,
    bin,
    brand,
    issuer_name,
    country_code,
    meta_data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (bin) DO UPDATE SET
    active = EXCLUDED.active,
    brand = EXCLUDED.brand,
    issuer_name = EXCLUDED.issuer_name,
    country_code = EXCLUDED.country_code,
    meta_data = EXCLUDED.meta_data,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, identifier, active, bin, brand, issuer_name, country_code, meta_data, created_at, updated_at, deleted_at
`

type EnsureIssuerBinParams struct {
	Active      bool        `json:"active"`
	Bin         string      `json:"bin"`
	Brand       CardNetwork `json:"brand"`
	IssuerName  string      `json:"issuer_name"`
	CountryCode string      `json:"country_code"`
	MetaData    []byte      `json:"meta_data"`
}

func (q *Queries) EnsureIssuerBin(ctx context.Context, arg EnsureIssuerBinParams) (IssuerBin, error) {
	row := q.db.QueryRow(ctx, ensureIssuerBin,
		arg.Active,
		arg.Bin,
		arg.Brand,
		arg.IssuerName,
		arg.CountryCode,
		arg.MetaData,
	)
	var i IssuerBin
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Active,
		&i.Bin,
		&i.Brand,
		&i.IssuerName,
		&i.CountryCode,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveWalletCardByWallet = `-- name: GetActiveWalletCardByWallet :one
SELECT id, identifier, wallet_id, wallet_identifier, user_identifier, card_product_id, issuer_bin, brand, pan_fingerprint, masked_pan, pan_last4, expiry_month, expiry_year, cardholder_name, service_code, cvv_digest, cvv_two_digest, track1_digest, track2_digest, pin_digest, last_authenticated_at, status, meta_data, created_at, updated_at, deleted_at FROM wallet_cards
WHERE wallet_identifier = $1
AND user_identifier = $2
AND status = 'ACTIVE'
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveWalletCardByWalletParams struct {
	WalletIdentifier string `json:"wallet_identifier"`
	UserIdentifier   string `json:"user_identifier"`
}

func (q *Queries) GetActiveWalletCardByWallet(ctx context.Context, arg GetActiveWalletCardByWalletParams) (WalletCard, error) {
	row := q.db.QueryRow(ctx, getActiveWalletCardByWallet, arg.WalletIdentifier, arg.UserIdentifier)
	var i WalletCard
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.WalletID,
		&i.WalletIdentifier,
		&i.UserIdentifier,
		&i.CardProductID,
		&i.IssuerBin,
		&i.Brand,
		&i.PanFingerprint,
		&i.MaskedPan,
		&i.PanLast4,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.CardholderName,
		&i.ServiceCode,
		&i.CvvDigest,
		&i.CvvTwoDigest,
		&i.Track1Digest,
		&i.Track2Digest,
		&i.PinDigest,
		&i.LastAuthenticatedAt,
		&i.Status,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletCardByPanFingerprint = `-- name: GetWalletCardByPanFingerprint :one
SELECT id, identifier, wallet_id, wallet_identifier, user_identifier, card_product_id, issuer_bin, brand, pan_fingerprint, masked_pan, pan_last4, expiry_month, expiry_year, cardholder_name, service_code, cvv_digest, cvv_two_digest, track1_digest, track2_digest, pin_digest, last_authenticated_at, status, meta_data, created_at, updated_at, deleted_at FROM wallet_cards
WHERE pan_fingerprint = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWalletCardByPanFingerprint(ctx context.Context, panFingerprint string) (WalletCard, error) {
	row := q.db.QueryRow(ctx, getWalletCardByPanFingerprint, panFingerprint)
	var i WalletCard
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.WalletID,
		&i.WalletIdentifier,
		&i.UserIdentifier,
		&i.CardProductID,
		&i.IssuerBin,
		&i.Brand,
		&i.PanFingerprint,
		&i.MaskedPan,
		&i.PanLast4,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.CardholderName,
		&i.ServiceCode,
		&i.CvvDigest,
		&i.CvvTwoDigest,
		&i.Track1Digest,
		&i.Track2Digest,
		&i.PinDigest,
		&i.LastAuthenticatedAt,
		&i.Status,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletCardsByWallet = `-- name: GetWalletCardsByWallet :many
SELECT id, identifier, wallet_id, wallet_identifier, user_identifier, card_product_id, issuer_bin, brand, pan_fingerprint, masked_pan, pan_last4, expiry_month, expiry_year, cardholder_name, service_code, cvv_digest, cvv_two_digest, track1_digest, track2_digest, pin_digest, last_authenticated_at, status, meta_data, created_at, updated_at, deleted_at FROM wallet_cards
WHERE wallet_identifier = $1
AND user_identifier = $2
AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetWalletCardsByWalletParams struct {
	WalletIdentifier string `json:"wallet_identifier"`
	UserIdentifier   string `json:"user_identifier"`
}

func (q *Queries) GetWalletCardsByWallet(ctx context.Context, arg GetWalletCardsByWalletParams) ([]WalletCard, error) {
	rows, err := q.db.Query(ctx, getWalletCardsByWallet, arg.WalletIdentifier, arg.UserIdentifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletCard{}
	for rows.Next() {
		var i WalletCard
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.WalletID,
			&i.WalletIdentifier,
			&i.UserIdentifier,
			&i.CardProductID,
			&i.IssuerBin,
			&i.Brand,
			&i.PanFingerprint,
			&i.MaskedPan,
			&i.PanLast4,
			&i.ExpiryMonth,
			&i.ExpiryYear,
			&i.CardholderName,
			&i.ServiceCode,
			&i.CvvDigest,
			&i.CvvTwoDigest,
			&i.Track1Digest,
			&i.Track2Digest,
			&i.PinDigest,
			&i.LastAuthenticatedAt,
			&i.Status,
			&i.MetaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletCardLastAuthenticatedAt = `-- name: UpdateWalletCardLastAuthenticatedAt :one
UPDATE wallet_cards
SET last_authenticated_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, identifier, wallet_id, wallet_identifier, user_identifier, card_product_id, issuer_bin, brand, pan_fingerprint, masked_pan, pan_last4, expiry_month, expiry_year, cardholder_name, service_code, cvv_digest, cvv_two_digest, track1_digest, track2_digest, pin_digest, last_authenticated_at, status, meta_data, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateWalletCardLastAuthenticatedAt(ctx context.Context, id int64) (WalletCard, error) {
	row := q.db.QueryRow(ctx, updateWalletCardLastAuthenticatedAt, id)
	var i WalletCard
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.WalletID,
		&i.WalletIdentifier,
		&i.UserIdentifier,
		&i.CardProductID,
		&i.IssuerBin,
		&i.Brand,
		&i.PanFingerprint,
		&i.MaskedPan,
		&i.PanLast4,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.CardholderName,
		&i.ServiceCode,
		&i.CvvDigest,
		&i.CvvTwoDigest,
		&i.Track1Digest,
		&i.Track2Digest,
		&i.PinDigest,
		&i.LastAuthenticatedAt,
		&i.Status,
		&i.MetaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
