// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

type AccountStatus string

const (
	AccountStatusPENDING AccountStatus = "PENDING"
	AccountStatusISSUED  AccountStatus = "ISSUED"
	AccountStatusACTIVE  AccountStatus = "ACTIVE"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type CardNetwork string

const (
	CardNetworkLOCAL      CardNetwork = "LOCAL"
	CardNetworkVISA       CardNetwork = "VISA"
	CardNetworkMASTERCARD CardNetwork = "MASTERCARD"
	CardNetworkAMEX       CardNetwork = "AMEX"
)

func (e *CardNetwork) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardNetwork(s)
	case string:
		*e = CardNetwork(s)
	default:
		return fmt.Errorf("unsupported scan type for CardNetwork: %T", src)
	}
	return nil
}

type NullCardNetwork struct {
	CardNetwork CardNetwork `json:"card_network"`
	Valid       bool        `json:"valid"` // Valid is true if CardNetwork is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardNetwork) Scan(value interface{}) error {
	if value == nil {
		ns.CardNetwork, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardNetwork.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardNetwork) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardNetwork), nil
}

type WalletAccountStatus string

const (
	WalletAccountStatusPENDING      WalletAccountStatus = "PENDING"
	WalletAccountStatusACTIVE       WalletAccountStatus = "ACTIVE"
	WalletAccountStatusINACTIVE     WalletAccountStatus = "INACTIVE"
	WalletAccountStatusBANNED       WalletAccountStatus = "BANNED"
	WalletAccountStatusLOCKED       WalletAccountStatus = "LOCKED"
	WalletAccountStatusLINKEDLOCKED WalletAccountStatus = "LINKED_LOCKED"
)

func (e *WalletAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletAccountStatus(s)
	case string:
		*e = WalletAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletAccountStatus: %T", src)
	}
	return nil
}

type NullWalletAccountStatus struct {
	WalletAccountStatus WalletAccountStatus `json:"wallet_account_status"`
	Valid               bool                `json:"valid"` // Valid is true if WalletAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WalletAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletAccountStatus), nil
}

type WalletAssetUnit string

const (
	WalletAssetUnitNONE      WalletAssetUnit = "NONE"
	WalletAssetUnitMILLIGRAM WalletAssetUnit = "MILLIGRAM"
	WalletAssetUnitGRAM      WalletAssetUnit = "GRAM"
	WalletAssetUnitKILOGRAM  WalletAssetUnit = "KILOGRAM"
	WalletAssetUnitTONNE     WalletAssetUnit = "TONNE"
	WalletAssetUnitPIECE     WalletAssetUnit = "PIECE"
)

func (e *WalletAssetUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletAssetUnit(s)
	case string:
		*e = WalletAssetUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletAssetUnit: %T", src)
	}
	return nil
}

type NullWalletAssetUnit struct {
	WalletAssetUnit WalletAssetUnit `json:"wallet_asset_unit"`
	Valid           bool            `json:"valid"` // Valid is true if WalletAssetUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletAssetUnit) Scan(value interface{}) error {
	if value == nil {
		ns.WalletAssetUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletAssetUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletAssetUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletAssetUnit), nil
}

type WalletCardEventType string

const (
	WalletCardEventTypeISSUED               WalletCardEventType = "ISSUED"
	WalletCardEventTypeAUTHENTICATED        WalletCardEventType = "AUTHENTICATED"
	WalletCardEventTypeAUTHENTICATIONFAILED WalletCardEventType = "AUTHENTICATION_FAILED"
	WalletCardEventTypeSTATUSCHANGED        WalletCardEventType = "STATUS_CHANGED"
)

func (e *WalletCardEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletCardEventType(s)
	case string:
		*e = WalletCardEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletCardEventType: %T", src)
	}
	return nil
}

type NullWalletCardEventType struct {
	WalletCardEventType WalletCardEventType `json:"wallet_card_event_type"`
	Valid               bool                `json:"valid"` // Valid is true if WalletCardEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletCardEventType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletCardEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletCardEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletCardEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletCardEventType), nil
}

type WalletCardStatus string

const (
	WalletCardStatusPENDING  WalletCardStatus = "PENDING"
	WalletCardStatusACTIVE   WalletCardStatus = "ACTIVE"
	WalletCardStatusINACTIVE WalletCardStatus = "INACTIVE"
	WalletCardStatusBLOCKED  WalletCardStatus = "BLOCKED"
	WalletCardStatusEXPIRED  WalletCardStatus = "EXPIRED"
	WalletCardStatusREISSUED WalletCardStatus = "REISSUED"
)

func (e *WalletCardStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletCardStatus(s)
	case string:
		*e = WalletCardStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletCardStatus: %T", src)
	}
	return nil
}

type NullWalletCardStatus struct {
	WalletCardStatus WalletCardStatus `json:"wallet_card_status"`
	Valid            bool             `json:"valid"` // Valid is true if WalletCardStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletCardStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WalletCardStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletCardStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletCardStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletCardStatus), nil
}

type Account struct {
	// account unique id
	ID int64 `json:"id"`
	// unique external identifier for inter system internal-external identifier separation
	Identifier ulid.ULID `json:"identifier"`
	// account title
	Title string `json:"title"`
	// account description
	Description pgtype.Text `json:"description"`
	// account status
	Status AccountStatus `json:"status"`
	// is account banned or no
	Banned bool `json:"banned"`
	// related user identifier to determining account owner account
	UserIdentifier string `json:"user_identifier"`
	// related base asset identifier to determining account base asset
	BaseAssetIdentifier string `json:"base_asset_identifier"`
	// account meta data
	MetaData []byte `json:"meta_data"`
	// expire time of account, if not sets then user valid for unlimited time
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// when account was created
	CreatedAt time.Time `json:"created_at"`
	// when account was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when account was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type CardProduct struct {
	// card product unique id
	ID int64 `json:"id"`
	// unique external identifier for card product
	Identifier ulid.ULID `json:"identifier"`
	// related issuer bin id for this card product
	IssuerBinID int64 `json:"issuer_bin_id"`
	// card product name
	Name string `json:"name"`
	// configured PAN length for this product
	PanLength int32 `json:"pan_length"`
	// configured CVV/CVV2 length for this product
	CvvLength int32 `json:"cvv_length"`
	// default expiry policy in months
	ExpiryMonths int32 `json:"expiry_months"`
	// magnetic stripe service code
	ServiceCode string `json:"service_code"`
	// is magnetic stripe issuance allowed
	AllowMagneticStripe bool `json:"allow_magnetic_stripe"`
	// card product meta data
	MetaData []byte `json:"meta_data"`
	// when card product was created
	CreatedAt time.Time `json:"created_at"`
	// when card product was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when card product was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type IssuerBin struct {
	// issuer bin unique id
	ID int64 `json:"id"`
	// unique external identifier for issuer bin
	Identifier ulid.ULID `json:"identifier"`
	// is issuer bin active or no
	Active bool `json:"active"`
	// issuer identification number / bank identification number
	Bin string `json:"bin"`
	// card network / brand
	Brand CardNetwork `json:"brand"`
	// issuer display name
	IssuerName string `json:"issuer_name"`
	// issuer ISO country code
	CountryCode string `json:"country_code"`
	// issuer bin meta data
	MetaData []byte `json:"meta_data"`
	// when issuer bin was created
	CreatedAt time.Time `json:"created_at"`
	// when issuer bin was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when issuer bin was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Wallet struct {
	// wallet unique id
	ID int64 `json:"id"`
	// unique external identifier for inter system internal-external identifier separation
	Identifier ulid.ULID `json:"identifier"`
	// related user identifier to determining account owner
	UserIdentifier string `json:"user_identifier"`
	// related account identifier to determining account of wallet
	AccountIdentifier string `json:"account_identifier"`
	// related account id to determining account of wallet
	AccountID int64 `json:"account_id"`
	// related asset identifier to determining asset of wallet
	AssetIdentifier string `json:"asset_identifier"`
	// related wallet asset id to determining asset of wallet
	WalletAssetID int64 `json:"wallet_asset_id"`
	// wallet account meta data
	MetaData []byte `json:"meta_data"`
	// related ledger account id to determining "ledger account" of wallet in ledger core
	LedgerAccountID int64 `json:"ledger_account_id"`
	// related ledger account code to determining service code for wallet in ledger core
	LedgerAccountCode int32 `json:"ledger_account_code"`
	// primary account number of wallet account
	PrimaryAccountNumber string `json:"primary_account_number"`
	// IBAN of wallet account
	Iban pgtype.Text `json:"iban"`
	// CVV of wallet account
	Cvv pgtype.Text `json:"cvv"`
	// CVV2 of wallet account
	CvvTwo pgtype.Text `json:"cvv_two"`
	// expire date of wallet account
	ExpireDate pgtype.Text `json:"expire_date"`
	// PIN code of wallet account (bcrypted)
	PinCode pgtype.Text `json:"pin_code"`
	// wallet account status
	Status WalletAccountStatus `json:"status"`
	// transaction TOTP secret for wallet account (bcrypted)
	TransactionTotpSecret pgtype.Text `json:"transaction_totp_secret"`
	// transaction TOTP secret expire time for wallet account
	TransactionTotpExpiresAt pgtype.Timestamptz `json:"transaction_totp_expires_at"`
	// when wallet account was created
	CreatedAt time.Time `json:"created_at"`
	// when wallet account was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when wallet account was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type WalletAsset struct {
	// wallet_asset unique id
	ID int64 `json:"id"`
	// unique external identifier for inter system internal-external identifier separation
	Identifier ulid.ULID `json:"identifier"`
	// is wallet asset active or no
	Active bool `json:"active"`
	// asset code of wallet asset
	Code string `json:"code"`
	// asset symbol of wallet asset
	Symbol string `json:"symbol"`
	// wallet asset title
	Title string `json:"title"`
	// wallet asset description
	Description pgtype.Text `json:"description"`
	// is wallet asset predefined for account initialization or no
	Predefined bool `json:"predefined"`
	// wallet asset unit
	Unit WalletAssetUnit `json:"unit"`
	// wallet asset unit title
	UnitTitle pgtype.Text `json:"unit_title"`
	// wallet asset decimals
	Decimals int32 `json:"decimals"`
	// wallet asset network
	Network pgtype.Text `json:"network"`
	// wallet asset icon url
	IconUrl pgtype.Text `json:"icon_url"`
	// wallet asset meta data
	MetaData []byte `json:"meta_data"`
	// related ledger code to determining wallet in ledger
	LedgerCode int32 `json:"ledger_code"`
	// when wallet asset was created
	CreatedAt time.Time `json:"created_at"`
	// when wallet asset was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when wallet asset was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type WalletCard struct {
	// wallet card unique id
	ID int64 `json:"id"`
	// unique external identifier for wallet card
	Identifier ulid.ULID `json:"identifier"`
	// related wallet id
	WalletID int64 `json:"wallet_id"`
	// related wallet identifier
	WalletIdentifier string `json:"wallet_identifier"`
	// related user identifier
	UserIdentifier string `json:"user_identifier"`
	// related card product id
	CardProductID int64 `json:"card_product_id"`
	// issuer bin used for card generation
	IssuerBin string `json:"issuer_bin"`
	// card network / brand
	Brand CardNetwork `json:"brand"`
	// stable HMAC-based PAN fingerprint used for lookup
	PanFingerprint string `json:"pan_fingerprint"`
	// masked PAN for display only
	MaskedPan string `json:"masked_pan"`
	// last 4 PAN digits
	PanLast4 string `json:"pan_last4"`
	// card expiry month in MM form
	ExpiryMonth int32 `json:"expiry_month"`
	// card expiry year in YYYY form
	ExpiryYear int32 `json:"expiry_year"`
	// normalized cardholder name for embossing/track generation
	CardholderName string `json:"cardholder_name"`
	// magnetic stripe service code
	ServiceCode string `json:"service_code"`
	// HMAC digest of CVV verification material
	CvvDigest string `json:"cvv_digest"`
	// HMAC digest of CVV2 verification material
	CvvTwoDigest string `json:"cvv_two_digest"`
	// HMAC digest of generated track1 data
	Track1Digest pgtype.Text `json:"track1_digest"`
	// HMAC digest of generated track2 data
	Track2Digest string `json:"track2_digest"`
	// digest or delegated reference for PIN material
	PinDigest pgtype.Text `json:"pin_digest"`
	// when card was last authenticated successfully
	LastAuthenticatedAt pgtype.Timestamptz `json:"last_authenticated_at"`
	// wallet card lifecycle status
	Status WalletCardStatus `json:"status"`
	// wallet card meta data
	MetaData []byte `json:"meta_data"`
	// when wallet card was created
	CreatedAt time.Time `json:"created_at"`
	// when wallet card was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when wallet card was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type WalletCardEvent struct {
	// wallet card event unique id
	ID int64 `json:"id"`
	// unique external identifier for wallet card event
	Identifier ulid.ULID `json:"identifier"`
	// related wallet card id
	WalletCardID int64 `json:"wallet_card_id"`
	// related wallet card identifier
	WalletCardIdentifier string `json:"wallet_card_identifier"`
	// related user identifier
	UserIdentifier string `json:"user_identifier"`
	// wallet card event type
	EventType WalletCardEventType `json:"event_type"`
	// event success flag
	Success bool `json:"success"`
	// remote ip address of requester if available
	RemoteIp pgtype.Text `json:"remote_ip"`
	// wallet card event meta data
	MetaData []byte `json:"meta_data"`
	// when wallet card event was created
	CreatedAt time.Time `json:"created_at"`
}
