// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

type AccountStatus string

const (
	AccountStatusPENDING AccountStatus = "PENDING"
	AccountStatusISSUED  AccountStatus = "ISSUED"
	AccountStatusACTIVE  AccountStatus = "ACTIVE"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type WalletAccountStatus string

const (
	WalletAccountStatusPENDING      WalletAccountStatus = "PENDING"
	WalletAccountStatusACTIVE       WalletAccountStatus = "ACTIVE"
	WalletAccountStatusINACTIVE     WalletAccountStatus = "INACTIVE"
	WalletAccountStatusBANNED       WalletAccountStatus = "BANNED"
	WalletAccountStatusLOCKED       WalletAccountStatus = "LOCKED"
	WalletAccountStatusLINKEDLOCKED WalletAccountStatus = "LINKED_LOCKED"
)

func (e *WalletAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletAccountStatus(s)
	case string:
		*e = WalletAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletAccountStatus: %T", src)
	}
	return nil
}

type NullWalletAccountStatus struct {
	WalletAccountStatus WalletAccountStatus `json:"wallet_account_status"`
	Valid               bool                `json:"valid"` // Valid is true if WalletAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WalletAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletAccountStatus), nil
}

type WalletAssetUnit string

const (
	WalletAssetUnitNONE      WalletAssetUnit = "NONE"
	WalletAssetUnitMILLIGRAM WalletAssetUnit = "MILLIGRAM"
	WalletAssetUnitGRAM      WalletAssetUnit = "GRAM"
	WalletAssetUnitKILOGRAM  WalletAssetUnit = "KILOGRAM"
	WalletAssetUnitTONNE     WalletAssetUnit = "TONNE"
	WalletAssetUnitPIECE     WalletAssetUnit = "PIECE"
)

func (e *WalletAssetUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletAssetUnit(s)
	case string:
		*e = WalletAssetUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletAssetUnit: %T", src)
	}
	return nil
}

type NullWalletAssetUnit struct {
	WalletAssetUnit WalletAssetUnit `json:"wallet_asset_unit"`
	Valid           bool            `json:"valid"` // Valid is true if WalletAssetUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletAssetUnit) Scan(value interface{}) error {
	if value == nil {
		ns.WalletAssetUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletAssetUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletAssetUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletAssetUnit), nil
}

type Account struct {
	// account unique id
	ID int64 `json:"id"`
	// unique external identifier for inter system internal-external identifier separation
	Identifier ulid.ULID `json:"identifier"`
	// account title
	Title string `json:"title"`
	// account description
	Description pgtype.Text `json:"description"`
	// account status
	Status AccountStatus `json:"status"`
	// is account banned or no
	Banned bool `json:"banned"`
	// related user identifier to determining account owner account
	UserIdentifier string `json:"user_identifier"`
	// related base asset identifier to determining account base asset
	BaseAssetIdentifier string `json:"base_asset_identifier"`
	// account meta data
	MetaData []byte `json:"meta_data"`
	// expire time of account, if not sets then user valid for unlimited time
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// when account was created
	CreatedAt time.Time `json:"created_at"`
	// when account was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when account was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Wallet struct {
	// wallet unique id
	ID int64 `json:"id"`
	// unique external identifier for inter system internal-external identifier separation
	Identifier ulid.ULID `json:"identifier"`
	// related user identifier to determining account owner
	UserIdentifier string `json:"user_identifier"`
	// related account identifier to determining account of wallet
	AccountIdentifier string `json:"account_identifier"`
	// related account id to determining account of wallet
	AccountID int64 `json:"account_id"`
	// related asset identifier to determining asset of wallet
	AssetIdentifier string `json:"asset_identifier"`
	// related wallet asset id to determining asset of wallet
	WalletAssetID int64 `json:"wallet_asset_id"`
	// wallet account meta data
	MetaData []byte `json:"meta_data"`
	// related ledger account id to determining "ledger account" of wallet in ledger core
	LedgerAccountID []byte `json:"ledger_account_id"`
	// related ledger account code to determining service code for wallet in ledger core
	LedgerAccountCode int32 `json:"ledger_account_code"`
	// primary account number of wallet account
	PrimaryAccountNumber string `json:"primary_account_number"`
	// IBAN of wallet account
	Iban pgtype.Text `json:"iban"`
	// CVV of wallet account
	Cvv pgtype.Text `json:"cvv"`
	// CVV2 of wallet account
	CvvTwo pgtype.Text `json:"cvv_two"`
	// expire date of wallet account
	ExpireDate pgtype.Text `json:"expire_date"`
	// PIN code of wallet account (bcrypted)
	PinCode pgtype.Text `json:"pin_code"`
	// wallet account status
	Status WalletAccountStatus `json:"status"`
	// transaction TOTP secret for wallet account (bcrypted)
	TransactionTotpSecret pgtype.Text `json:"transaction_totp_secret"`
	// transaction TOTP secret expire time for wallet account
	TransactionTotpExpiresAt pgtype.Timestamptz `json:"transaction_totp_expires_at"`
	// when wallet account was created
	CreatedAt time.Time `json:"created_at"`
	// when wallet account was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when wallet account was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type WalletAsset struct {
	// wallet_asset unique id
	ID int64 `json:"id"`
	// unique external identifier for inter system internal-external identifier separation
	Identifier ulid.ULID `json:"identifier"`
	// is wallet asset active or no
	Active bool `json:"active"`
	// asset code of wallet asset
	Code string `json:"code"`
	// asset symbol of wallet asset
	Symbol string `json:"symbol"`
	// wallet asset title
	Title string `json:"title"`
	// wallet asset description
	Description pgtype.Text `json:"description"`
	// is wallet asset predefined for account initialization or no
	Predefined bool `json:"predefined"`
	// wallet asset unit
	Unit WalletAssetUnit `json:"unit"`
	// wallet asset unit title
	UnitTitle pgtype.Text `json:"unit_title"`
	// wallet asset decimals
	Decimals int32 `json:"decimals"`
	// wallet asset network
	Network pgtype.Text `json:"network"`
	// wallet asset icon url
	IconUrl pgtype.Text `json:"icon_url"`
	// wallet asset meta data
	MetaData []byte `json:"meta_data"`
	// related ledger code to determining wallet in ledger
	LedgerCode int32 `json:"ledger_code"`
	// when wallet asset was created
	CreatedAt time.Time `json:"created_at"`
	// when wallet asset was updated
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// when wallet asset was deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
