// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO sessions (
        user_id,
        expires_in,
        notification,
        meta_data,
        host,
        device_id,
        device_name,
        device_user_agent,
        device_notification_token,
        created_at,
        updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        (CURRENT_TIMESTAMP),
        (CURRENT_TIMESTAMP)
    )
RETURNING id, host, device_id, device_name, device_user_agent, device_notification_token, identifier, user_id, expires_in, notification, meta_data, created_at, deleted_at, updated_at
`

type CreateUserSessionParams struct {
	UserID                  int64       `json:"user_id"`
	ExpiresIn               time.Time   `json:"expires_in"`
	Notification            pgtype.Text `json:"notification"`
	MetaData                []byte      `json:"meta_data"`
	Host                    string      `json:"host"`
	DeviceID                string      `json:"device_id"`
	DeviceName              string      `json:"device_name"`
	DeviceUserAgent         []byte      `json:"device_user_agent"`
	DeviceNotificationToken pgtype.Text `json:"device_notification_token"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.ExpiresIn,
		arg.Notification,
		arg.MetaData,
		arg.Host,
		arg.DeviceID,
		arg.DeviceName,
		arg.DeviceUserAgent,
		arg.DeviceNotificationToken,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceUserAgent,
		&i.DeviceNotificationToken,
		&i.Identifier,
		&i.UserID,
		&i.ExpiresIn,
		&i.Notification,
		&i.MetaData,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, host, device_id, device_name, device_user_agent, device_notification_token, identifier, user_id, expires_in, notification, meta_data, created_at, deleted_at, updated_at
FROM sessions
WHERE id = $1
    AND user_id = $2
    AND deleted_at IS NULL
LIMIT 1
`

type GetSessionByIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetSessionById(ctx context.Context, arg GetSessionByIdParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionById, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceUserAgent,
		&i.DeviceNotificationToken,
		&i.Identifier,
		&i.UserID,
		&i.ExpiresIn,
		&i.Notification,
		&i.MetaData,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewUserSession = `-- name: RenewUserSession :one
UPDATE sessions
SET
    (meta_data, updated_at, expires_in) = ($3, (CURRENT_TIMESTAMP), $4)
WHERE
    sessions.user_id = $1
    AND sessions.id = $2
    AND sessions.deleted_at IS NULL
RETURNING
    id, host, device_id, device_name, device_user_agent, device_notification_token, identifier, user_id, expires_in, notification, meta_data, created_at, deleted_at, updated_at
`

type RenewUserSessionParams struct {
	UserID    int64     `json:"user_id"`
	ID        int64     `json:"id"`
	MetaData  []byte    `json:"meta_data"`
	ExpiresIn time.Time `json:"expires_in"`
}

func (q *Queries) RenewUserSession(ctx context.Context, arg RenewUserSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, renewUserSession,
		arg.UserID,
		arg.ID,
		arg.MetaData,
		arg.ExpiresIn,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceUserAgent,
		&i.DeviceNotificationToken,
		&i.Identifier,
		&i.UserID,
		&i.ExpiresIn,
		&i.Notification,
		&i.MetaData,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
