// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

const getUserAssetWallet = `-- name: GetUserAssetWallet :one
SELECT wallets.identifier, wallets.user_identifier, account_identifier, asset_identifier, wallets.meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, wallets.status, transaction_totp_secret, transaction_totp_expires_at, wallets.created_at, wallets.updated_at, wallets.deleted_at, wallet_assets.identifier, active, code, symbol, wallet_assets.title, wallet_assets.description, wallet_assets.meta_data, ledger_code, wallet_assets.created_at, wallet_assets.updated_at, wallet_assets.deleted_at, accounts.identifier, accounts.title, accounts.description, accounts.status, banned, accounts.user_identifier, base_asset_identifier, accounts.meta_data, expires_at, accounts.created_at, accounts.updated_at, accounts.deleted_at FROM wallets
JOIN wallet_assets ON wallets.base_asset_identifier = wallet_assets.identifier
JOIN accounts ON wallets.user_identifier = accounts.identifier
WHERE accounts.identifier = $1
AND accounts.status != 'PENDING'
AND accounts.deleted_at IS NULL
AND accounts.banned = FALSE
AND accounts.expires_at > NOW()
AND wallet_assets.symbol = $2
AND wallet_assets.active = TRUE
AND wallet_assets.deleted_at IS NULL
AND wallets.user_identifier = $1
AND wallets.base_asset_identifier = wallet_assets.identifier
AND wallets.deleted_at IS NULL
LIMIT 1
`

type GetUserAssetWalletParams struct {
	Identifier ulid.ULID `json:"identifier"`
	Symbol     string    `json:"symbol"`
}

type GetUserAssetWalletRow struct {
	Identifier               ulid.ULID           `json:"identifier"`
	UserIdentifier           ulid.ULID           `json:"user_identifier"`
	AccountIdentifier        ulid.ULID           `json:"account_identifier"`
	AssetIdentifier          int64               `json:"asset_identifier"`
	MetaData                 []byte              `json:"meta_data"`
	LedgerAccountID          interface{}         `json:"ledger_account_id"`
	LedgerAccountCode        int32               `json:"ledger_account_code"`
	PrimaryAccountNumber     string              `json:"primary_account_number"`
	Iban                     pgtype.Text         `json:"iban"`
	Cvv                      pgtype.Text         `json:"cvv"`
	CvvTwo                   pgtype.Text         `json:"cvv_two"`
	ExpireDate               pgtype.Text         `json:"expire_date"`
	PinCode                  pgtype.Text         `json:"pin_code"`
	Status                   WalletAccountStatus `json:"status"`
	TransactionTotpSecret    pgtype.Text         `json:"transaction_totp_secret"`
	TransactionTotpExpiresAt pgtype.Timestamptz  `json:"transaction_totp_expires_at"`
	CreatedAt                time.Time           `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz  `json:"deleted_at"`
	Identifier_2             ulid.ULID           `json:"identifier_2"`
	Active                   bool                `json:"active"`
	Code                     string              `json:"code"`
	Symbol                   string              `json:"symbol"`
	Title                    string              `json:"title"`
	Description              pgtype.Text         `json:"description"`
	MetaData_2               []byte              `json:"meta_data_2"`
	LedgerCode               int32               `json:"ledger_code"`
	CreatedAt_2              time.Time           `json:"created_at_2"`
	UpdatedAt_2              pgtype.Timestamptz  `json:"updated_at_2"`
	DeletedAt_2              pgtype.Timestamptz  `json:"deleted_at_2"`
	Identifier_3             ulid.ULID           `json:"identifier_3"`
	Title_2                  string              `json:"title_2"`
	Description_2            pgtype.Text         `json:"description_2"`
	Status_2                 AccountStatus       `json:"status_2"`
	Banned                   bool                `json:"banned"`
	UserIdentifier_2         ulid.ULID           `json:"user_identifier_2"`
	BaseAssetIdentifier      ulid.ULID           `json:"base_asset_identifier"`
	MetaData_3               []byte              `json:"meta_data_3"`
	ExpiresAt                pgtype.Timestamptz  `json:"expires_at"`
	CreatedAt_3              time.Time           `json:"created_at_3"`
	UpdatedAt_3              pgtype.Timestamptz  `json:"updated_at_3"`
	DeletedAt_3              pgtype.Timestamptz  `json:"deleted_at_3"`
}

// join accounts, wallets and wallet_assets tables to get wallet and base asset information
// 1: select account with specified user identifier if it status that is enum is not 'PENDING' , deleted_at IS NULL and banned is FALSE and expires_at after now
// 2 : get wallet asset by symbol if active field IS TRUE and deleted_at IS NULL
// 3 : get wallet by user identifier and base asset identifier that match with input user identifier and base asset identifier selected in step 2
//
//	3-1: selected wallet asset deleted_at IS NULL
//	3-3: selected wallet deleted_at IS NULL
func (q *Queries) GetUserAssetWallet(ctx context.Context, arg GetUserAssetWalletParams) (GetUserAssetWalletRow, error) {
	row := q.db.QueryRow(ctx, getUserAssetWallet, arg.Identifier, arg.Symbol)
	var i GetUserAssetWalletRow
	err := row.Scan(
		&i.Identifier,
		&i.UserIdentifier,
		&i.AccountIdentifier,
		&i.AssetIdentifier,
		&i.MetaData,
		&i.LedgerAccountID,
		&i.LedgerAccountCode,
		&i.PrimaryAccountNumber,
		&i.Iban,
		&i.Cvv,
		&i.CvvTwo,
		&i.ExpireDate,
		&i.PinCode,
		&i.Status,
		&i.TransactionTotpSecret,
		&i.TransactionTotpExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Identifier_2,
		&i.Active,
		&i.Code,
		&i.Symbol,
		&i.Title,
		&i.Description,
		&i.MetaData_2,
		&i.LedgerCode,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
		&i.Identifier_3,
		&i.Title_2,
		&i.Description_2,
		&i.Status_2,
		&i.Banned,
		&i.UserIdentifier_2,
		&i.BaseAssetIdentifier,
		&i.MetaData_3,
		&i.ExpiresAt,
		&i.CreatedAt_3,
		&i.UpdatedAt_3,
		&i.DeletedAt_3,
	)
	return i, err
}

const getUserWallets = `-- name: GetUserWallets :many
SELECT identifier, user_identifier, account_identifier, asset_identifier, meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, status, transaction_totp_secret, transaction_totp_expires_at, created_at, updated_at, deleted_at FROM wallets
WHERE user_identifier = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserWalletsParams struct {
	UserIdentifier ulid.ULID `json:"user_identifier"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) GetUserWallets(ctx context.Context, arg GetUserWalletsParams) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, getUserWallets, arg.UserIdentifier, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.Identifier,
			&i.UserIdentifier,
			&i.AccountIdentifier,
			&i.AssetIdentifier,
			&i.MetaData,
			&i.LedgerAccountID,
			&i.LedgerAccountCode,
			&i.PrimaryAccountNumber,
			&i.Iban,
			&i.Cvv,
			&i.CvvTwo,
			&i.ExpireDate,
			&i.PinCode,
			&i.Status,
			&i.TransactionTotpSecret,
			&i.TransactionTotpExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletByIdentifier = `-- name: GetWalletByIdentifier :one
SELECT identifier, user_identifier, account_identifier, asset_identifier, meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, status, transaction_totp_secret, transaction_totp_expires_at, created_at, updated_at, deleted_at FROM wallets
WHERE identifier = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWalletByIdentifier(ctx context.Context, identifier ulid.ULID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByIdentifier, identifier)
	var i Wallet
	err := row.Scan(
		&i.Identifier,
		&i.UserIdentifier,
		&i.AccountIdentifier,
		&i.AssetIdentifier,
		&i.MetaData,
		&i.LedgerAccountID,
		&i.LedgerAccountCode,
		&i.PrimaryAccountNumber,
		&i.Iban,
		&i.Cvv,
		&i.CvvTwo,
		&i.ExpireDate,
		&i.PinCode,
		&i.Status,
		&i.TransactionTotpSecret,
		&i.TransactionTotpExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
