// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    user_identifier,
    account_identifier,
    account_id,
    asset_identifier,
    wallet_asset_id,
    meta_data,
    ledger_account_id,
    ledger_account_code,
    primary_account_number,
    iban,
    cvv,
    cvv_two,
    expire_date,
    pin_code,
    status,
    created_at,
    updated_at
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
)
RETURNING id, identifier, user_identifier, account_identifier, account_id, asset_identifier, wallet_asset_id, meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, status, transaction_totp_secret, transaction_totp_expires_at, created_at, updated_at, deleted_at
`

type CreateWalletParams struct {
	UserIdentifier       string              `json:"user_identifier"`
	AccountIdentifier    string              `json:"account_identifier"`
	AccountID            int64               `json:"account_id"`
	AssetIdentifier      string              `json:"asset_identifier"`
	WalletAssetID        int64               `json:"wallet_asset_id"`
	MetaData             []byte              `json:"meta_data"`
	LedgerAccountID      int64               `json:"ledger_account_id"`
	LedgerAccountCode    int32               `json:"ledger_account_code"`
	PrimaryAccountNumber string              `json:"primary_account_number"`
	Iban                 pgtype.Text         `json:"iban"`
	Cvv                  pgtype.Text         `json:"cvv"`
	CvvTwo               pgtype.Text         `json:"cvv_two"`
	ExpireDate           pgtype.Text         `json:"expire_date"`
	PinCode              pgtype.Text         `json:"pin_code"`
	Status               WalletAccountStatus `json:"status"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.UserIdentifier,
		arg.AccountIdentifier,
		arg.AccountID,
		arg.AssetIdentifier,
		arg.WalletAssetID,
		arg.MetaData,
		arg.LedgerAccountID,
		arg.LedgerAccountCode,
		arg.PrimaryAccountNumber,
		arg.Iban,
		arg.Cvv,
		arg.CvvTwo,
		arg.ExpireDate,
		arg.PinCode,
		arg.Status,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.UserIdentifier,
		&i.AccountIdentifier,
		&i.AccountID,
		&i.AssetIdentifier,
		&i.WalletAssetID,
		&i.MetaData,
		&i.LedgerAccountID,
		&i.LedgerAccountCode,
		&i.PrimaryAccountNumber,
		&i.Iban,
		&i.Cvv,
		&i.CvvTwo,
		&i.ExpireDate,
		&i.PinCode,
		&i.Status,
		&i.TransactionTotpSecret,
		&i.TransactionTotpExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAssetWallet = `-- name: GetUserAssetWallet :one
SELECT wallets.id, wallets.identifier, wallets.user_identifier, wallets.account_identifier, wallets.account_id, wallets.asset_identifier, wallets.wallet_asset_id, wallets.meta_data, wallets.ledger_account_id, wallets.ledger_account_code, wallets.primary_account_number, wallets.iban, wallets.cvv, wallets.cvv_two, wallets.expire_date, wallets.pin_code, wallets.status, wallets.transaction_totp_secret, wallets.transaction_totp_expires_at, wallets.created_at, wallets.updated_at, wallets.deleted_at FROM wallets
JOIN wallet_assets ON wallets.wallet_asset_id = wallet_assets.id
JOIN accounts ON wallets.account_id = accounts.id
WHERE accounts.user_identifier = $1
AND accounts.status != 'PENDING'
AND accounts.deleted_at IS NULL
AND accounts.banned = FALSE
AND (accounts.expires_at IS NULL OR accounts.expires_at > NOW())
AND wallet_assets.symbol = $2
AND wallet_assets.active = TRUE
AND wallet_assets.deleted_at IS NULL
AND wallets.user_identifier = $1
AND wallets.deleted_at IS NULL
LIMIT 1
`

type GetUserAssetWalletParams struct {
	UserIdentifier string `json:"user_identifier"`
	Symbol         string `json:"symbol"`
}

// join accounts, wallets and wallet_assets tables to get wallet and base asset information
// 1: select account with specified user identifier if it status that is enum is not 'PENDING' , deleted_at IS NULL and banned is FALSE and expires_at after now
// 2 : get wallet asset by symbol if active field IS TRUE and deleted_at IS NULL
// 3 : get wallet by user identifier and base asset identifier that match with input user identifier and base asset identifier selected in step 2
//
//	3-1: selected wallet asset deleted_at IS NULL
//	3-3: selected wallet deleted_at IS NULL
func (q *Queries) GetUserAssetWallet(ctx context.Context, arg GetUserAssetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getUserAssetWallet, arg.UserIdentifier, arg.Symbol)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.UserIdentifier,
		&i.AccountIdentifier,
		&i.AccountID,
		&i.AssetIdentifier,
		&i.WalletAssetID,
		&i.MetaData,
		&i.LedgerAccountID,
		&i.LedgerAccountCode,
		&i.PrimaryAccountNumber,
		&i.Iban,
		&i.Cvv,
		&i.CvvTwo,
		&i.ExpireDate,
		&i.PinCode,
		&i.Status,
		&i.TransactionTotpSecret,
		&i.TransactionTotpExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserWalletByIdentifier = `-- name: GetUserWalletByIdentifier :one
SELECT id, identifier, user_identifier, account_identifier, account_id, asset_identifier, wallet_asset_id, meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, status, transaction_totp_secret, transaction_totp_expires_at, created_at, updated_at, deleted_at FROM wallets
WHERE identifier::text = $1::text
AND user_identifier = $2
AND deleted_at IS NULL
LIMIT 1
`

type GetUserWalletByIdentifierParams struct {
	Column1        string `json:"column_1"`
	UserIdentifier string `json:"user_identifier"`
}

func (q *Queries) GetUserWalletByIdentifier(ctx context.Context, arg GetUserWalletByIdentifierParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getUserWalletByIdentifier, arg.Column1, arg.UserIdentifier)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.UserIdentifier,
		&i.AccountIdentifier,
		&i.AccountID,
		&i.AssetIdentifier,
		&i.WalletAssetID,
		&i.MetaData,
		&i.LedgerAccountID,
		&i.LedgerAccountCode,
		&i.PrimaryAccountNumber,
		&i.Iban,
		&i.Cvv,
		&i.CvvTwo,
		&i.ExpireDate,
		&i.PinCode,
		&i.Status,
		&i.TransactionTotpSecret,
		&i.TransactionTotpExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserWallets = `-- name: GetUserWallets :many
SELECT id, identifier, user_identifier, account_identifier, account_id, asset_identifier, wallet_asset_id, meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, status, transaction_totp_secret, transaction_totp_expires_at, created_at, updated_at, deleted_at FROM wallets
WHERE user_identifier = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserWalletsParams struct {
	UserIdentifier string `json:"user_identifier"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) GetUserWallets(ctx context.Context, arg GetUserWalletsParams) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, getUserWallets, arg.UserIdentifier, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.UserIdentifier,
			&i.AccountIdentifier,
			&i.AccountID,
			&i.AssetIdentifier,
			&i.WalletAssetID,
			&i.MetaData,
			&i.LedgerAccountID,
			&i.LedgerAccountCode,
			&i.PrimaryAccountNumber,
			&i.Iban,
			&i.Cvv,
			&i.CvvTwo,
			&i.ExpireDate,
			&i.PinCode,
			&i.Status,
			&i.TransactionTotpSecret,
			&i.TransactionTotpExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletByIdentifier = `-- name: GetWalletByIdentifier :one
SELECT id, identifier, user_identifier, account_identifier, account_id, asset_identifier, wallet_asset_id, meta_data, ledger_account_id, ledger_account_code, primary_account_number, iban, cvv, cvv_two, expire_date, pin_code, status, transaction_totp_secret, transaction_totp_expires_at, created_at, updated_at, deleted_at FROM wallets
WHERE identifier::text = $1::text
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetWalletByIdentifier(ctx context.Context, dollar_1 string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByIdentifier, dollar_1)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.UserIdentifier,
		&i.AccountIdentifier,
		&i.AccountID,
		&i.AssetIdentifier,
		&i.WalletAssetID,
		&i.MetaData,
		&i.LedgerAccountID,
		&i.LedgerAccountCode,
		&i.PrimaryAccountNumber,
		&i.Iban,
		&i.Cvv,
		&i.CvvTwo,
		&i.ExpireDate,
		&i.PinCode,
		&i.Status,
		&i.TransactionTotpSecret,
		&i.TransactionTotpExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
